// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/pb/fleet/fleet.proto

package fleet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_GetVehicles_FullMethodName              = "/fleet.FleetService/GetVehicles"
	FleetService_GetVehicle_FullMethodName               = "/fleet.FleetService/GetVehicle"
	FleetService_SearchVehicles_FullMethodName           = "/fleet.FleetService/SearchVehicles"
	FleetService_GetVehicleAvailability_FullMethodName   = "/fleet.FleetService/GetVehicleAvailability"
	FleetService_CheckVehicleAvailability_FullMethodName = "/fleet.FleetService/CheckVehicleAvailability"
	FleetService_LockVehicle_FullMethodName              = "/fleet.FleetService/LockVehicle"
	FleetService_UnlockVehicle_FullMethodName            = "/fleet.FleetService/UnlockVehicle"
	FleetService_UpdateVehicleLocation_FullMethodName    = "/fleet.FleetService/UpdateVehicleLocation"
	FleetService_GetVehicleLocation_FullMethodName       = "/fleet.FleetService/GetVehicleLocation"
	FleetService_GetNearbyVehicles_FullMethodName        = "/fleet.FleetService/GetNearbyVehicles"
	FleetService_GetOffices_FullMethodName               = "/fleet.FleetService/GetOffices"
	FleetService_GetOffice_FullMethodName                = "/fleet.FleetService/GetOffice"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetServiceClient interface {
	// Vehicle Operations
	GetVehicles(ctx context.Context, in *GetVehiclesRequest, opts ...grpc.CallOption) (*GetVehiclesResponse, error)
	GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*GetVehicleResponse, error)
	SearchVehicles(ctx context.Context, in *SearchVehiclesRequest, opts ...grpc.CallOption) (*SearchVehiclesResponse, error)
	GetVehicleAvailability(ctx context.Context, in *GetVehicleAvailabilityRequest, opts ...grpc.CallOption) (*GetVehicleAvailabilityResponse, error)
	CheckVehicleAvailability(ctx context.Context, in *CheckVehicleAvailabilityRequest, opts ...grpc.CallOption) (*CheckVehicleAvailabilityResponse, error)
	LockVehicle(ctx context.Context, in *LockVehicleRequest, opts ...grpc.CallOption) (*Response, error)
	UnlockVehicle(ctx context.Context, in *UnlockVehicleRequest, opts ...grpc.CallOption) (*Response, error)
	// Location & Tracking
	UpdateVehicleLocation(ctx context.Context, in *UpdateVehicleLocationRequest, opts ...grpc.CallOption) (*Response, error)
	GetVehicleLocation(ctx context.Context, in *GetVehicleLocationRequest, opts ...grpc.CallOption) (*GetVehicleLocationResponse, error)
	GetNearbyVehicles(ctx context.Context, in *GetNearbyVehiclesRequest, opts ...grpc.CallOption) (*GetNearbyVehiclesResponse, error)
	// Office Operations
	GetOffices(ctx context.Context, in *GetOfficesRequest, opts ...grpc.CallOption) (*GetOfficesResponse, error)
	GetOffice(ctx context.Context, in *GetOfficeRequest, opts ...grpc.CallOption) (*GetOfficeResponse, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) GetVehicles(ctx context.Context, in *GetVehiclesRequest, opts ...grpc.CallOption) (*GetVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVehiclesResponse)
	err := c.cc.Invoke(ctx, FleetService_GetVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*GetVehicleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVehicleResponse)
	err := c.cc.Invoke(ctx, FleetService_GetVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SearchVehicles(ctx context.Context, in *SearchVehiclesRequest, opts ...grpc.CallOption) (*SearchVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVehiclesResponse)
	err := c.cc.Invoke(ctx, FleetService_SearchVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetVehicleAvailability(ctx context.Context, in *GetVehicleAvailabilityRequest, opts ...grpc.CallOption) (*GetVehicleAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVehicleAvailabilityResponse)
	err := c.cc.Invoke(ctx, FleetService_GetVehicleAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CheckVehicleAvailability(ctx context.Context, in *CheckVehicleAvailabilityRequest, opts ...grpc.CallOption) (*CheckVehicleAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckVehicleAvailabilityResponse)
	err := c.cc.Invoke(ctx, FleetService_CheckVehicleAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) LockVehicle(ctx context.Context, in *LockVehicleRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FleetService_LockVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) UnlockVehicle(ctx context.Context, in *UnlockVehicleRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FleetService_UnlockVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) UpdateVehicleLocation(ctx context.Context, in *UpdateVehicleLocationRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FleetService_UpdateVehicleLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetVehicleLocation(ctx context.Context, in *GetVehicleLocationRequest, opts ...grpc.CallOption) (*GetVehicleLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVehicleLocationResponse)
	err := c.cc.Invoke(ctx, FleetService_GetVehicleLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetNearbyVehicles(ctx context.Context, in *GetNearbyVehiclesRequest, opts ...grpc.CallOption) (*GetNearbyVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNearbyVehiclesResponse)
	err := c.cc.Invoke(ctx, FleetService_GetNearbyVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetOffices(ctx context.Context, in *GetOfficesRequest, opts ...grpc.CallOption) (*GetOfficesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOfficesResponse)
	err := c.cc.Invoke(ctx, FleetService_GetOffices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetOffice(ctx context.Context, in *GetOfficeRequest, opts ...grpc.CallOption) (*GetOfficeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOfficeResponse)
	err := c.cc.Invoke(ctx, FleetService_GetOffice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
type FleetServiceServer interface {
	// Vehicle Operations
	GetVehicles(context.Context, *GetVehiclesRequest) (*GetVehiclesResponse, error)
	GetVehicle(context.Context, *GetVehicleRequest) (*GetVehicleResponse, error)
	SearchVehicles(context.Context, *SearchVehiclesRequest) (*SearchVehiclesResponse, error)
	GetVehicleAvailability(context.Context, *GetVehicleAvailabilityRequest) (*GetVehicleAvailabilityResponse, error)
	CheckVehicleAvailability(context.Context, *CheckVehicleAvailabilityRequest) (*CheckVehicleAvailabilityResponse, error)
	LockVehicle(context.Context, *LockVehicleRequest) (*Response, error)
	UnlockVehicle(context.Context, *UnlockVehicleRequest) (*Response, error)
	// Location & Tracking
	UpdateVehicleLocation(context.Context, *UpdateVehicleLocationRequest) (*Response, error)
	GetVehicleLocation(context.Context, *GetVehicleLocationRequest) (*GetVehicleLocationResponse, error)
	GetNearbyVehicles(context.Context, *GetNearbyVehiclesRequest) (*GetNearbyVehiclesResponse, error)
	// Office Operations
	GetOffices(context.Context, *GetOfficesRequest) (*GetOfficesResponse, error)
	GetOffice(context.Context, *GetOfficeRequest) (*GetOfficeResponse, error)
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) GetVehicles(context.Context, *GetVehiclesRequest) (*GetVehiclesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicles not implemented")
}
func (UnimplementedFleetServiceServer) GetVehicle(context.Context, *GetVehicleRequest) (*GetVehicleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicle not implemented")
}
func (UnimplementedFleetServiceServer) SearchVehicles(context.Context, *SearchVehiclesRequest) (*SearchVehiclesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchVehicles not implemented")
}
func (UnimplementedFleetServiceServer) GetVehicleAvailability(context.Context, *GetVehicleAvailabilityRequest) (*GetVehicleAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicleAvailability not implemented")
}
func (UnimplementedFleetServiceServer) CheckVehicleAvailability(context.Context, *CheckVehicleAvailabilityRequest) (*CheckVehicleAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVehicleAvailability not implemented")
}
func (UnimplementedFleetServiceServer) LockVehicle(context.Context, *LockVehicleRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockVehicle not implemented")
}
func (UnimplementedFleetServiceServer) UnlockVehicle(context.Context, *UnlockVehicleRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockVehicle not implemented")
}
func (UnimplementedFleetServiceServer) UpdateVehicleLocation(context.Context, *UpdateVehicleLocationRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVehicleLocation not implemented")
}
func (UnimplementedFleetServiceServer) GetVehicleLocation(context.Context, *GetVehicleLocationRequest) (*GetVehicleLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicleLocation not implemented")
}
func (UnimplementedFleetServiceServer) GetNearbyVehicles(context.Context, *GetNearbyVehiclesRequest) (*GetNearbyVehiclesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearbyVehicles not implemented")
}
func (UnimplementedFleetServiceServer) GetOffices(context.Context, *GetOfficesRequest) (*GetOfficesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffices not implemented")
}
func (UnimplementedFleetServiceServer) GetOffice(context.Context, *GetOfficeRequest) (*GetOfficeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffice not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call pancis, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_GetVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetVehicles(ctx, req.(*GetVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetVehicle(ctx, req.(*GetVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SearchVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SearchVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SearchVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SearchVehicles(ctx, req.(*SearchVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetVehicleAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetVehicleAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetVehicleAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetVehicleAvailability(ctx, req.(*GetVehicleAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CheckVehicleAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVehicleAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CheckVehicleAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CheckVehicleAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CheckVehicleAvailability(ctx, req.(*CheckVehicleAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_LockVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).LockVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_LockVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).LockVehicle(ctx, req.(*LockVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_UnlockVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).UnlockVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_UnlockVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).UnlockVehicle(ctx, req.(*UnlockVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_UpdateVehicleLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehicleLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).UpdateVehicleLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_UpdateVehicleLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).UpdateVehicleLocation(ctx, req.(*UpdateVehicleLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetVehicleLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetVehicleLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetVehicleLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetVehicleLocation(ctx, req.(*GetVehicleLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetNearbyVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearbyVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetNearbyVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetNearbyVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetNearbyVehicles(ctx, req.(*GetNearbyVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetOffices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfficesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetOffices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetOffices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetOffices(ctx, req.(*GetOfficesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetOffice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfficeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetOffice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetOffice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetOffice(ctx, req.(*GetOfficeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVehicles",
			Handler:    _FleetService_GetVehicles_Handler,
		},
		{
			MethodName: "GetVehicle",
			Handler:    _FleetService_GetVehicle_Handler,
		},
		{
			MethodName: "SearchVehicles",
			Handler:    _FleetService_SearchVehicles_Handler,
		},
		{
			MethodName: "GetVehicleAvailability",
			Handler:    _FleetService_GetVehicleAvailability_Handler,
		},
		{
			MethodName: "CheckVehicleAvailability",
			Handler:    _FleetService_CheckVehicleAvailability_Handler,
		},
		{
			MethodName: "LockVehicle",
			Handler:    _FleetService_LockVehicle_Handler,
		},
		{
			MethodName: "UnlockVehicle",
			Handler:    _FleetService_UnlockVehicle_Handler,
		},
		{
			MethodName: "UpdateVehicleLocation",
			Handler:    _FleetService_UpdateVehicleLocation_Handler,
		},
		{
			MethodName: "GetVehicleLocation",
			Handler:    _FleetService_GetVehicleLocation_Handler,
		},
		{
			MethodName: "GetNearbyVehicles",
			Handler:    _FleetService_GetNearbyVehicles_Handler,
		},
		{
			MethodName: "GetOffices",
			Handler:    _FleetService_GetOffices_Handler,
		},
		{
			MethodName: "GetOffice",
			Handler:    _FleetService_GetOffice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/fleet/fleet.proto",
}
