// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/pb/fleet/fleet.proto

package fleet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_Status int32

const (
	Response_OK    Response_Status = 0
	Response_ERROR Response_Status = 1
)

// Enum value maps for Response_Status.
var (
	Response_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Response_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}

func (x Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_fleet_fleet_proto_enumTypes[0].Descriptor()
}

func (Response_Status) Type() protoreflect.EnumType {
	return &file_internal_pb_fleet_fleet_proto_enumTypes[0]
}

func (x Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Status.Descriptor instead.
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{0, 0}
}

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  Response_Status        `protobuf:"varint,1,opt,name=status,proto3,enum=fleet.Response_Status" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Error
	//	*Response_Data
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetStatus() Response_Status {
	if x != nil {
		return x.Status
	}
	return Response_OK
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Data); ok {
			return x.Data
		}
	}
	return ""
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Response_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*Response_Error) isResponse_Payload() {}

func (*Response_Data) isResponse_Payload() {}

// Vehicle Messages
type GetVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfficeId      uint32                 `protobuf:"varint,1,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "available", "booked", "maintenance", "all"
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehiclesRequest) Reset() {
	*x = GetVehiclesRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehiclesRequest) ProtoMessage() {}

func (x *GetVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehiclesRequest.ProtoReflect.Descriptor instead.
func (*GetVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *GetVehiclesRequest) GetOfficeId() uint32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *GetVehiclesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetVehiclesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetVehiclesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Vehicles      []*Vehicle             `protobuf:"bytes,2,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehiclesResponse) Reset() {
	*x = GetVehiclesResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehiclesResponse) ProtoMessage() {}

func (x *GetVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehiclesResponse.ProtoReflect.Descriptor instead.
func (*GetVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *GetVehiclesResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *GetVehiclesResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *GetVehicleRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Vehicle       *Vehicle               `protobuf:"bytes,2,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *GetVehicleResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type SearchVehiclesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PickupDate     string                 `protobuf:"bytes,1,opt,name=pickup_date,json=pickupDate,proto3" json:"pickup_date,omitempty"`
	ReturnDate     string                 `protobuf:"bytes,2,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	PickupOfficeId uint32                 `protobuf:"varint,3,opt,name=pickup_office_id,json=pickupOfficeId,proto3" json:"pickup_office_id,omitempty"`
	ReturnOfficeId uint32                 `protobuf:"varint,4,opt,name=return_office_id,json=returnOfficeId,proto3" json:"return_office_id,omitempty"`
	VehicleType    string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"` // "car", "bike", "all"
	Transmission   string                 `protobuf:"bytes,6,opt,name=transmission,proto3" json:"transmission,omitempty"`                  // "manual", "automatic", "all"
	FuelType       string                 `protobuf:"bytes,7,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`          // "petrol", "diesel", "electric", "all"
	MinPrice       float64                `protobuf:"fixed64,8,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice       float64                `protobuf:"fixed64,9,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Limit          uint32                 `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         uint32                 `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchVehiclesRequest) Reset() {
	*x = SearchVehiclesRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVehiclesRequest) ProtoMessage() {}

func (x *SearchVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVehiclesRequest.ProtoReflect.Descriptor instead.
func (*SearchVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *SearchVehiclesRequest) GetPickupDate() string {
	if x != nil {
		return x.PickupDate
	}
	return ""
}

func (x *SearchVehiclesRequest) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *SearchVehiclesRequest) GetPickupOfficeId() uint32 {
	if x != nil {
		return x.PickupOfficeId
	}
	return 0
}

func (x *SearchVehiclesRequest) GetReturnOfficeId() uint32 {
	if x != nil {
		return x.ReturnOfficeId
	}
	return 0
}

func (x *SearchVehiclesRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *SearchVehiclesRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *SearchVehiclesRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *SearchVehiclesRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchVehiclesRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchVehiclesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchVehiclesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Vehicles      []*Vehicle             `protobuf:"bytes,2,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVehiclesResponse) Reset() {
	*x = SearchVehiclesResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVehiclesResponse) ProtoMessage() {}

func (x *SearchVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVehiclesResponse.ProtoReflect.Descriptor instead.
func (*SearchVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *SearchVehiclesResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SearchVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *SearchVehiclesResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetVehicleAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleAvailabilityRequest) Reset() {
	*x = GetVehicleAvailabilityRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleAvailabilityRequest) ProtoMessage() {}

func (x *GetVehicleAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *GetVehicleAvailabilityRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *GetVehicleAvailabilityRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetVehicleAvailabilityRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetVehicleAvailabilityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Response          *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Available         bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	NextAvailableDate string                 `protobuf:"bytes,3,opt,name=next_available_date,json=nextAvailableDate,proto3" json:"next_available_date,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetVehicleAvailabilityResponse) Reset() {
	*x = GetVehicleAvailabilityResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleAvailabilityResponse) ProtoMessage() {}

func (x *GetVehicleAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *GetVehicleAvailabilityResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetVehicleAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *GetVehicleAvailabilityResponse) GetNextAvailableDate() string {
	if x != nil {
		return x.NextAvailableDate
	}
	return ""
}

type CheckVehicleAvailabilityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleId      uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	PickupDate     string                 `protobuf:"bytes,2,opt,name=pickup_date,json=pickupDate,proto3" json:"pickup_date,omitempty"`
	ReturnDate     string                 `protobuf:"bytes,3,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	PickupOfficeId uint32                 `protobuf:"varint,4,opt,name=pickup_office_id,json=pickupOfficeId,proto3" json:"pickup_office_id,omitempty"`
	ReturnOfficeId uint32                 `protobuf:"varint,5,opt,name=return_office_id,json=returnOfficeId,proto3" json:"return_office_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckVehicleAvailabilityRequest) Reset() {
	*x = CheckVehicleAvailabilityRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVehicleAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVehicleAvailabilityRequest) ProtoMessage() {}

func (x *CheckVehicleAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVehicleAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckVehicleAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *CheckVehicleAvailabilityRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *CheckVehicleAvailabilityRequest) GetPickupDate() string {
	if x != nil {
		return x.PickupDate
	}
	return ""
}

func (x *CheckVehicleAvailabilityRequest) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *CheckVehicleAvailabilityRequest) GetPickupOfficeId() uint32 {
	if x != nil {
		return x.PickupOfficeId
	}
	return 0
}

func (x *CheckVehicleAvailabilityRequest) GetReturnOfficeId() uint32 {
	if x != nil {
		return x.ReturnOfficeId
	}
	return 0
}

type CheckVehicleAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	BaseCost      float64                `protobuf:"fixed64,4,opt,name=base_cost,json=baseCost,proto3" json:"base_cost,omitempty"`
	Deposit       float64                `protobuf:"fixed64,5,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVehicleAvailabilityResponse) Reset() {
	*x = CheckVehicleAvailabilityResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVehicleAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVehicleAvailabilityResponse) ProtoMessage() {}

func (x *CheckVehicleAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVehicleAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckVehicleAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *CheckVehicleAvailabilityResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CheckVehicleAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckVehicleAvailabilityResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *CheckVehicleAvailabilityResponse) GetBaseCost() float64 {
	if x != nil {
		return x.BaseCost
	}
	return 0
}

func (x *CheckVehicleAvailabilityResponse) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

type LockVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LockDuration  string                 `protobuf:"bytes,3,opt,name=lock_duration,json=lockDuration,proto3" json:"lock_duration,omitempty"` // ISO 8601 duration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockVehicleRequest) Reset() {
	*x = LockVehicleRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockVehicleRequest) ProtoMessage() {}

func (x *LockVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockVehicleRequest.ProtoReflect.Descriptor instead.
func (*LockVehicleRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *LockVehicleRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *LockVehicleRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockVehicleRequest) GetLockDuration() string {
	if x != nil {
		return x.LockDuration
	}
	return ""
}

type UnlockVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockVehicleRequest) Reset() {
	*x = UnlockVehicleRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockVehicleRequest) ProtoMessage() {}

func (x *UnlockVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockVehicleRequest.ProtoReflect.Descriptor instead.
func (*UnlockVehicleRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *UnlockVehicleRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *UnlockVehicleRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Location Messages
type UpdateVehicleLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,5,opt,name=heading,proto3" json:"heading,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleLocationRequest) Reset() {
	*x = UpdateVehicleLocationRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleLocationRequest) ProtoMessage() {}

func (x *UpdateVehicleLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleLocationRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateVehicleLocationRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *UpdateVehicleLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateVehicleLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateVehicleLocationRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *UpdateVehicleLocationRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *UpdateVehicleLocationRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetVehicleLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleLocationRequest) Reset() {
	*x = GetVehicleLocationRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleLocationRequest) ProtoMessage() {}

func (x *GetVehicleLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleLocationRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleLocationRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *GetVehicleLocationRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type GetVehicleLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleLocationResponse) Reset() {
	*x = GetVehicleLocationResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleLocationResponse) ProtoMessage() {}

func (x *GetVehicleLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleLocationResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleLocationResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{15}
}

func (x *GetVehicleLocationResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetVehicleLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetNearbyVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	VehicleType   string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyVehiclesRequest) Reset() {
	*x = GetNearbyVehiclesRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyVehiclesRequest) ProtoMessage() {}

func (x *GetNearbyVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyVehiclesRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{16}
}

func (x *GetNearbyVehiclesRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetNearbyVehiclesRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetNearbyVehiclesRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *GetNearbyVehiclesRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *GetNearbyVehiclesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNearbyVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Vehicles      []*VehicleLocation     `protobuf:"bytes,2,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyVehiclesResponse) Reset() {
	*x = GetNearbyVehiclesResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyVehiclesResponse) ProtoMessage() {}

func (x *GetNearbyVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyVehiclesResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{17}
}

func (x *GetNearbyVehiclesResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetNearbyVehiclesResponse) GetVehicles() []*VehicleLocation {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

// Office Messages
type GetOfficesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfficesRequest) Reset() {
	*x = GetOfficesRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfficesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficesRequest) ProtoMessage() {}

func (x *GetOfficesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficesRequest.ProtoReflect.Descriptor instead.
func (*GetOfficesRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{18}
}

func (x *GetOfficesRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetOfficesRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetOfficesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOfficesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetOfficesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Offices       []*Office              `protobuf:"bytes,2,rep,name=offices,proto3" json:"offices,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfficesResponse) Reset() {
	*x = GetOfficesResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfficesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficesResponse) ProtoMessage() {}

func (x *GetOfficesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficesResponse.ProtoReflect.Descriptor instead.
func (*GetOfficesResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{19}
}

func (x *GetOfficesResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetOfficesResponse) GetOffices() []*Office {
	if x != nil {
		return x.Offices
	}
	return nil
}

func (x *GetOfficesResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetOfficeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfficeId      uint32                 `protobuf:"varint,1,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfficeRequest) Reset() {
	*x = GetOfficeRequest{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficeRequest) ProtoMessage() {}

func (x *GetOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficeRequest.ProtoReflect.Descriptor instead.
func (*GetOfficeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{20}
}

func (x *GetOfficeRequest) GetOfficeId() uint32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

type GetOfficeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Office        *Office                `protobuf:"bytes,2,opt,name=office,proto3" json:"office,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfficeResponse) Reset() {
	*x = GetOfficeResponse{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfficeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficeResponse) ProtoMessage() {}

func (x *GetOfficeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficeResponse.ProtoReflect.Descriptor instead.
func (*GetOfficeResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{21}
}

func (x *GetOfficeResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetOfficeResponse) GetOffice() *Office {
	if x != nil {
		return x.Office
	}
	return nil
}

// Data Models
type Vehicle struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VehicleId          uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "car", "bike"
	Brand              string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Model              string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Year               uint32                 `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	Transmission       string                 `protobuf:"bytes,7,opt,name=transmission,proto3" json:"transmission,omitempty"`         // "manual", "automatic"
	FuelType           string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"` // "petrol", "diesel", "electric"
	Color              string                 `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"`
	SeatingCapacity    uint32                 `protobuf:"varint,10,opt,name=seating_capacity,json=seatingCapacity,proto3" json:"seating_capacity,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,11,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	DailyRate          float64                `protobuf:"fixed64,12,opt,name=daily_rate,json=dailyRate,proto3" json:"daily_rate,omitempty"`
	HourlyRate         float64                `protobuf:"fixed64,13,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	DepositAmount      float64                `protobuf:"fixed64,14,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
	Status             string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"` // "available", "booked", "maintenance", "out_of_service"
	OfficeId           uint32                 `protobuf:"varint,16,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,17,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Features           []string               `protobuf:"bytes,18,rep,name=features,proto3" json:"features,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Office             *Office                `protobuf:"bytes,21,opt,name=office,proto3" json:"office,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{22}
}

func (x *Vehicle) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Vehicle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vehicle) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Vehicle) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Vehicle) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *Vehicle) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *Vehicle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Vehicle) GetSeatingCapacity() uint32 {
	if x != nil {
		return x.SeatingCapacity
	}
	return 0
}

func (x *Vehicle) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *Vehicle) GetDailyRate() float64 {
	if x != nil {
		return x.DailyRate
	}
	return 0
}

func (x *Vehicle) GetHourlyRate() float64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *Vehicle) GetDepositAmount() float64 {
	if x != nil {
		return x.DepositAmount
	}
	return 0
}

func (x *Vehicle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Vehicle) GetOfficeId() uint32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *Vehicle) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Vehicle) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Vehicle) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Vehicle) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Vehicle) GetOffice() *Office {
	if x != nil {
		return x.Office
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,5,opt,name=heading,proto3" json:"heading,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{23}
}

func (x *Location) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Location) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *Location) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VehicleLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,3,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleLocation) Reset() {
	*x = VehicleLocation{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleLocation) ProtoMessage() {}

func (x *VehicleLocation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleLocation.ProtoReflect.Descriptor instead.
func (*VehicleLocation) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{24}
}

func (x *VehicleLocation) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *VehicleLocation) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *VehicleLocation) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type Office struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OfficeId       uint32                 `protobuf:"varint,1,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	City           string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Zip            uint32                 `protobuf:"varint,6,opt,name=zip,proto3" json:"zip,omitempty"`
	Phone          string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Email          string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Latitude       float64                `protobuf:"fixed64,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,10,opt,name=longitude,proto3" json:"longitude,omitempty"`
	OperatingHours string                 `protobuf:"bytes,11,opt,name=operating_hours,json=operatingHours,proto3" json:"operating_hours,omitempty"`
	ContactPerson  string                 `protobuf:"bytes,12,opt,name=contact_person,json=contactPerson,proto3" json:"contact_person,omitempty"`
	Status         string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"` // "active", "inactive"
	CreatedAt      string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Office) Reset() {
	*x = Office{}
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Office) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Office) ProtoMessage() {}

func (x *Office) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_fleet_fleet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Office.ProtoReflect.Descriptor instead.
func (*Office) Descriptor() ([]byte, []int) {
	return file_internal_pb_fleet_fleet_proto_rawDescGZIP(), []int{25}
}

func (x *Office) GetOfficeId() uint32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *Office) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Office) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Office) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Office) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Office) GetZip() uint32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

func (x *Office) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Office) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Office) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Office) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Office) GetOperatingHours() string {
	if x != nil {
		return x.OperatingHours
	}
	return ""
}

func (x *Office) GetContactPerson() string {
	if x != nil {
		return x.ContactPerson
	}
	return ""
}

func (x *Office) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Office) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Office) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_internal_pb_fleet_fleet_proto protoreflect.FileDescriptor

const file_internal_pb_fleet_fleet_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/pb/fleet/fleet.proto\x12\x05fleet\"\xaa\x01\n" +
	"\bResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.fleet.Response.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x12\x14\n" +
	"\x04data\x18\x04 \x01(\tH\x00R\x04data\"\x1b\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01B\t\n" +
	"\apayload\"w\n" +
	"\x12GetVehiclesRequest\x12\x1b\n" +
	"\toffice_id\x18\x01 \x01(\rR\bofficeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"\x8f\x01\n" +
	"\x13GetVehiclesResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12*\n" +
	"\bvehicles\x18\x02 \x03(\v2\x0e.fleet.VehicleR\bvehicles\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"2\n" +
	"\x11GetVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\"k\n" +
	"\x12GetVehicleResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12(\n" +
	"\avehicle\x18\x02 \x01(\v2\x0e.fleet.VehicleR\avehicle\"\xf9\x02\n" +
	"\x15SearchVehiclesRequest\x12\x1f\n" +
	"\vpickup_date\x18\x01 \x01(\tR\n" +
	"pickupDate\x12\x1f\n" +
	"\vreturn_date\x18\x02 \x01(\tR\n" +
	"returnDate\x12(\n" +
	"\x10pickup_office_id\x18\x03 \x01(\rR\x0epickupOfficeId\x12(\n" +
	"\x10return_office_id\x18\x04 \x01(\rR\x0ereturnOfficeId\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\x12\"\n" +
	"\ftransmission\x18\x06 \x01(\tR\ftransmission\x12\x1b\n" +
	"\tfuel_type\x18\a \x01(\tR\bfuelType\x12\x1b\n" +
	"\tmin_price\x18\b \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\t \x01(\x01R\bmaxPrice\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\v \x01(\rR\x06offset\"\x92\x01\n" +
	"\x16SearchVehiclesResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12*\n" +
	"\bvehicles\x18\x02 \x03(\v2\x0e.fleet.VehicleR\bvehicles\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"x\n" +
	"\x1dGetVehicleAvailabilityRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\x9b\x01\n" +
	"\x1eGetVehicleAvailabilityResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12.\n" +
	"\x13next_available_date\x18\x03 \x01(\tR\x11nextAvailableDate\"\xd6\x01\n" +
	"\x1fCheckVehicleAvailabilityRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x1f\n" +
	"\vpickup_date\x18\x02 \x01(\tR\n" +
	"pickupDate\x12\x1f\n" +
	"\vreturn_date\x18\x03 \x01(\tR\n" +
	"returnDate\x12(\n" +
	"\x10pickup_office_id\x18\x04 \x01(\rR\x0epickupOfficeId\x12(\n" +
	"\x10return_office_id\x18\x05 \x01(\rR\x0ereturnOfficeId\"\xc3\x01\n" +
	" CheckVehicleAvailabilityResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x03 \x01(\x01R\ttotalCost\x12\x1b\n" +
	"\tbase_cost\x18\x04 \x01(\x01R\bbaseCost\x12\x18\n" +
	"\adeposit\x18\x05 \x01(\x01R\adeposit\"q\n" +
	"\x12LockVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12#\n" +
	"\rlock_duration\x18\x03 \x01(\tR\flockDuration\"N\n" +
	"\x14UnlockVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\xc5\x01\n" +
	"\x1cUpdateVehicleLocationRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x05 \x01(\x01R\aheading\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\":\n" +
	"\x19GetVehicleLocationRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\"v\n" +
	"\x1aGetVehicleLocationResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12+\n" +
	"\blocation\x18\x02 \x01(\v2\x0f.fleet.LocationR\blocation\"\xaa\x01\n" +
	"\x18GetNearbyVehiclesRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"|\n" +
	"\x19GetNearbyVehiclesResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x122\n" +
	"\bvehicles\x18\x02 \x03(\v2\x16.fleet.VehicleLocationR\bvehicles\"k\n" +
	"\x11GetOfficesRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"\x8b\x01\n" +
	"\x12GetOfficesResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12'\n" +
	"\aoffices\x18\x02 \x03(\v2\r.fleet.OfficeR\aoffices\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"/\n" +
	"\x10GetOfficeRequest\x12\x1b\n" +
	"\toffice_id\x18\x01 \x01(\rR\bofficeId\"g\n" +
	"\x11GetOfficeResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.fleet.ResponseR\bresponse\x12%\n" +
	"\x06office\x18\x02 \x01(\v2\r.fleet.OfficeR\x06office\"\xfd\x04\n" +
	"\aVehicle\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x06 \x01(\rR\x04year\x12\"\n" +
	"\ftransmission\x18\a \x01(\tR\ftransmission\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\x12\x14\n" +
	"\x05color\x18\t \x01(\tR\x05color\x12)\n" +
	"\x10seating_capacity\x18\n" +
	" \x01(\rR\x0fseatingCapacity\x12/\n" +
	"\x13registration_number\x18\v \x01(\tR\x12registrationNumber\x12\x1d\n" +
	"\n" +
	"daily_rate\x18\f \x01(\x01R\tdailyRate\x12\x1f\n" +
	"\vhourly_rate\x18\r \x01(\x01R\n" +
	"hourlyRate\x12%\n" +
	"\x0edeposit_amount\x18\x0e \x01(\x01R\rdepositAmount\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\x1b\n" +
	"\toffice_id\x18\x10 \x01(\rR\bofficeId\x12\x1b\n" +
	"\timage_url\x18\x11 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bfeatures\x18\x12 \x03(\tR\bfeatures\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\tR\tupdatedAt\x12%\n" +
	"\x06office\x18\x15 \x01(\v2\r.fleet.OfficeR\x06office\"\xcb\x01\n" +
	"\bLocation\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x05 \x01(\x01R\aheading\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\"\x89\x01\n" +
	"\x0fVehicleLocation\x12(\n" +
	"\avehicle\x18\x01 \x01(\v2\x0e.fleet.VehicleR\avehicle\x12+\n" +
	"\blocation\x18\x02 \x01(\v2\x0f.fleet.LocationR\blocation\x12\x1f\n" +
	"\vdistance_km\x18\x03 \x01(\x01R\n" +
	"distanceKm\"\x9b\x03\n" +
	"\x06Office\x12\x1b\n" +
	"\toffice_id\x18\x01 \x01(\rR\bofficeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x06 \x01(\rR\x03zip\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x1a\n" +
	"\blatitude\x18\t \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\n" +
	" \x01(\x01R\tlongitude\x12'\n" +
	"\x0foperating_hours\x18\v \x01(\tR\x0eoperatingHours\x12%\n" +
	"\x0econtact_person\x18\f \x01(\tR\rcontactPerson\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt2\xb9\a\n" +
	"\fFleetService\x12D\n" +
	"\vGetVehicles\x12\x19.fleet.GetVehiclesRequest\x1a\x1a.fleet.GetVehiclesResponse\x12A\n" +
	"\n" +
	"GetVehicle\x12\x18.fleet.GetVehicleRequest\x1a\x19.fleet.GetVehicleResponse\x12M\n" +
	"\x0eSearchVehicles\x12\x1c.fleet.SearchVehiclesRequest\x1a\x1d.fleet.SearchVehiclesResponse\x12e\n" +
	"\x16GetVehicleAvailability\x12$.fleet.GetVehicleAvailabilityRequest\x1a%.fleet.GetVehicleAvailabilityResponse\x12k\n" +
	"\x18CheckVehicleAvailability\x12&.fleet.CheckVehicleAvailabilityRequest\x1a'.fleet.CheckVehicleAvailabilityResponse\x129\n" +
	"\vLockVehicle\x12\x19.fleet.LockVehicleRequest\x1a\x0f.fleet.Response\x12=\n" +
	"\rUnlockVehicle\x12\x1b.fleet.UnlockVehicleRequest\x1a\x0f.fleet.Response\x12M\n" +
	"\x15UpdateVehicleLocation\x12#.fleet.UpdateVehicleLocationRequest\x1a\x0f.fleet.Response\x12Y\n" +
	"\x12GetVehicleLocation\x12 .fleet.GetVehicleLocationRequest\x1a!.fleet.GetVehicleLocationResponse\x12V\n" +
	"\x11GetNearbyVehicles\x12\x1f.fleet.GetNearbyVehiclesRequest\x1a .fleet.GetNearbyVehiclesResponse\x12A\n" +
	"\n" +
	"GetOffices\x12\x18.fleet.GetOfficesRequest\x1a\x19.fleet.GetOfficesResponse\x12>\n" +
	"\tGetOffice\x12\x17.fleet.GetOfficeRequest\x1a\x18.fleet.GetOfficeResponseBSZQgithub.com/yourorg/ultimate-rent-car/ultimate-rent-user-service/internal/pb/fleetb\x06proto3"

var (
	file_internal_pb_fleet_fleet_proto_rawDescOnce sync.Once
	file_internal_pb_fleet_fleet_proto_rawDescData []byte
)

func file_internal_pb_fleet_fleet_proto_rawDescGZIP() []byte {
	file_internal_pb_fleet_fleet_proto_rawDescOnce.Do(func() {
		file_internal_pb_fleet_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_fleet_fleet_proto_rawDesc), len(file_internal_pb_fleet_fleet_proto_rawDesc)))
	})
	return file_internal_pb_fleet_fleet_proto_rawDescData
}

var file_internal_pb_fleet_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_fleet_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_pb_fleet_fleet_proto_goTypes = []any{
	(Response_Status)(0),                     // 0: fleet.Response.Status
	(*Response)(nil),                         // 1: fleet.Response
	(*GetVehiclesRequest)(nil),               // 2: fleet.GetVehiclesRequest
	(*GetVehiclesResponse)(nil),              // 3: fleet.GetVehiclesResponse
	(*GetVehicleRequest)(nil),                // 4: fleet.GetVehicleRequest
	(*GetVehicleResponse)(nil),               // 5: fleet.GetVehicleResponse
	(*SearchVehiclesRequest)(nil),            // 6: fleet.SearchVehiclesRequest
	(*SearchVehiclesResponse)(nil),           // 7: fleet.SearchVehiclesResponse
	(*GetVehicleAvailabilityRequest)(nil),    // 8: fleet.GetVehicleAvailabilityRequest
	(*GetVehicleAvailabilityResponse)(nil),   // 9: fleet.GetVehicleAvailabilityResponse
	(*CheckVehicleAvailabilityRequest)(nil),  // 10: fleet.CheckVehicleAvailabilityRequest
	(*CheckVehicleAvailabilityResponse)(nil), // 11: fleet.CheckVehicleAvailabilityResponse
	(*LockVehicleRequest)(nil),               // 12: fleet.LockVehicleRequest
	(*UnlockVehicleRequest)(nil),             // 13: fleet.UnlockVehicleRequest
	(*UpdateVehicleLocationRequest)(nil),     // 14: fleet.UpdateVehicleLocationRequest
	(*GetVehicleLocationRequest)(nil),        // 15: fleet.GetVehicleLocationRequest
	(*GetVehicleLocationResponse)(nil),       // 16: fleet.GetVehicleLocationResponse
	(*GetNearbyVehiclesRequest)(nil),         // 17: fleet.GetNearbyVehiclesRequest
	(*GetNearbyVehiclesResponse)(nil),        // 18: fleet.GetNearbyVehiclesResponse
	(*GetOfficesRequest)(nil),                // 19: fleet.GetOfficesRequest
	(*GetOfficesResponse)(nil),               // 20: fleet.GetOfficesResponse
	(*GetOfficeRequest)(nil),                 // 21: fleet.GetOfficeRequest
	(*GetOfficeResponse)(nil),                // 22: fleet.GetOfficeResponse
	(*Vehicle)(nil),                          // 23: fleet.Vehicle
	(*Location)(nil),                         // 24: fleet.Location
	(*VehicleLocation)(nil),                  // 25: fleet.VehicleLocation
	(*Office)(nil),                           // 26: fleet.Office
}
var file_internal_pb_fleet_fleet_proto_depIdxs = []int32{
	0,  // 0: fleet.Response.status:type_name -> fleet.Response.Status
	1,  // 1: fleet.GetVehiclesResponse.response:type_name -> fleet.Response
	23, // 2: fleet.GetVehiclesResponse.vehicles:type_name -> fleet.Vehicle
	1,  // 3: fleet.GetVehicleResponse.response:type_name -> fleet.Response
	23, // 4: fleet.GetVehicleResponse.vehicle:type_name -> fleet.Vehicle
	1,  // 5: fleet.SearchVehiclesResponse.response:type_name -> fleet.Response
	23, // 6: fleet.SearchVehiclesResponse.vehicles:type_name -> fleet.Vehicle
	1,  // 7: fleet.GetVehicleAvailabilityResponse.response:type_name -> fleet.Response
	1,  // 8: fleet.CheckVehicleAvailabilityResponse.response:type_name -> fleet.Response
	1,  // 9: fleet.GetVehicleLocationResponse.response:type_name -> fleet.Response
	24, // 10: fleet.GetVehicleLocationResponse.location:type_name -> fleet.Location
	1,  // 11: fleet.GetNearbyVehiclesResponse.response:type_name -> fleet.Response
	25, // 12: fleet.GetNearbyVehiclesResponse.vehicles:type_name -> fleet.VehicleLocation
	1,  // 13: fleet.GetOfficesResponse.response:type_name -> fleet.Response
	26, // 14: fleet.GetOfficesResponse.offices:type_name -> fleet.Office
	1,  // 15: fleet.GetOfficeResponse.response:type_name -> fleet.Response
	26, // 16: fleet.GetOfficeResponse.office:type_name -> fleet.Office
	26, // 17: fleet.Vehicle.office:type_name -> fleet.Office
	23, // 18: fleet.VehicleLocation.vehicle:type_name -> fleet.Vehicle
	24, // 19: fleet.VehicleLocation.location:type_name -> fleet.Location
	2,  // 20: fleet.FleetService.GetVehicles:input_type -> fleet.GetVehiclesRequest
	4,  // 21: fleet.FleetService.GetVehicle:input_type -> fleet.GetVehicleRequest
	6,  // 22: fleet.FleetService.SearchVehicles:input_type -> fleet.SearchVehiclesRequest
	8,  // 23: fleet.FleetService.GetVehicleAvailability:input_type -> fleet.GetVehicleAvailabilityRequest
	10, // 24: fleet.FleetService.CheckVehicleAvailability:input_type -> fleet.CheckVehicleAvailabilityRequest
	12, // 25: fleet.FleetService.LockVehicle:input_type -> fleet.LockVehicleRequest
	13, // 26: fleet.FleetService.UnlockVehicle:input_type -> fleet.UnlockVehicleRequest
	14, // 27: fleet.FleetService.UpdateVehicleLocation:input_type -> fleet.UpdateVehicleLocationRequest
	15, // 28: fleet.FleetService.GetVehicleLocation:input_type -> fleet.GetVehicleLocationRequest
	17, // 29: fleet.FleetService.GetNearbyVehicles:input_type -> fleet.GetNearbyVehiclesRequest
	19, // 30: fleet.FleetService.GetOffices:input_type -> fleet.GetOfficesRequest
	21, // 31: fleet.FleetService.GetOffice:input_type -> fleet.GetOfficeRequest
	3,  // 32: fleet.FleetService.GetVehicles:output_type -> fleet.GetVehiclesResponse
	5,  // 33: fleet.FleetService.GetVehicle:output_type -> fleet.GetVehicleResponse
	7,  // 34: fleet.FleetService.SearchVehicles:output_type -> fleet.SearchVehiclesResponse
	9,  // 35: fleet.FleetService.GetVehicleAvailability:output_type -> fleet.GetVehicleAvailabilityResponse
	11, // 36: fleet.FleetService.CheckVehicleAvailability:output_type -> fleet.CheckVehicleAvailabilityResponse
	1,  // 37: fleet.FleetService.LockVehicle:output_type -> fleet.Response
	1,  // 38: fleet.FleetService.UnlockVehicle:output_type -> fleet.Response
	1,  // 39: fleet.FleetService.UpdateVehicleLocation:output_type -> fleet.Response
	16, // 40: fleet.FleetService.GetVehicleLocation:output_type -> fleet.GetVehicleLocationResponse
	18, // 41: fleet.FleetService.GetNearbyVehicles:output_type -> fleet.GetNearbyVehiclesResponse
	20, // 42: fleet.FleetService.GetOffices:output_type -> fleet.GetOfficesResponse
	22, // 43: fleet.FleetService.GetOffice:output_type -> fleet.GetOfficeResponse
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_pb_fleet_fleet_proto_init() }
func file_internal_pb_fleet_fleet_proto_init() {
	if File_internal_pb_fleet_fleet_proto != nil {
		return
	}
	file_internal_pb_fleet_fleet_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_Error)(nil),
		(*Response_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_fleet_fleet_proto_rawDesc), len(file_internal_pb_fleet_fleet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_fleet_fleet_proto_goTypes,
		DependencyIndexes: file_internal_pb_fleet_fleet_proto_depIdxs,
		EnumInfos:         file_internal_pb_fleet_fleet_proto_enumTypes,
		MessageInfos:      file_internal_pb_fleet_fleet_proto_msgTypes,
	}.Build()
	File_internal_pb_fleet_fleet_proto = out.File
	file_internal_pb_fleet_fleet_proto_goTypes = nil
	file_internal_pb_fleet_fleet_proto_depIdxs = nil
}
