// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/pb/booking/booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_Status int32

const (
	Response_OK    Response_Status = 0
	Response_ERROR Response_Status = 1
)

// Enum value maps for Response_Status.
var (
	Response_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Response_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}

func (x Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_booking_booking_proto_enumTypes[0].Descriptor()
}

func (Response_Status) Type() protoreflect.EnumType {
	return &file_internal_pb_booking_booking_proto_enumTypes[0]
}

func (x Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Status.Descriptor instead.
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{0, 0}
}

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  Response_Status        `protobuf:"varint,1,opt,name=status,proto3,enum=booking.Response_Status" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Error
	//	*Response_Data
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetStatus() Response_Status {
	if x != nil {
		return x.Status
	}
	return Response_OK
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Data); ok {
			return x.Data
		}
	}
	return ""
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Response_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*Response_Error) isResponse_Payload() {}

func (*Response_Data) isResponse_Payload() {}

// Booking Messages
type CreateBookingRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VehicleId          uint32                 `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	OfficeId           uint32                 `protobuf:"varint,3,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	PickupDate         string                 `protobuf:"bytes,4,opt,name=pickup_date,json=pickupDate,proto3" json:"pickup_date,omitempty"`
	ReturnDate         string                 `protobuf:"bytes,5,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	PickupTime         string                 `protobuf:"bytes,6,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	ReturnTime         string                 `protobuf:"bytes,7,opt,name=return_time,json=returnTime,proto3" json:"return_time,omitempty"`
	AdditionalServices []string               `protobuf:"bytes,8,rep,name=additional_services,json=additionalServices,proto3" json:"additional_services,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBookingRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *CreateBookingRequest) GetOfficeId() uint32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *CreateBookingRequest) GetPickupDate() string {
	if x != nil {
		return x.PickupDate
	}
	return ""
}

func (x *CreateBookingRequest) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *CreateBookingRequest) GetPickupTime() string {
	if x != nil {
		return x.PickupTime
	}
	return ""
}

func (x *CreateBookingRequest) GetReturnTime() string {
	if x != nil {
		return x.ReturnTime
	}
	return ""
}

func (x *CreateBookingRequest) GetAdditionalServices() []string {
	if x != nil {
		return x.AdditionalServices
	}
	return nil
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Booking       *Booking               `protobuf:"bytes,2,opt,name=booking,proto3" json:"booking,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,3,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookingResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *CreateBookingResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookingRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *GetBookingRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Booking       *Booking               `protobuf:"bytes,2,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookingResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetUserBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "all", "active", "completed", "cancelled"
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBookingsRequest) Reset() {
	*x = GetUserBookingsRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBookingsRequest) ProtoMessage() {}

func (x *GetUserBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBookingsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBookingsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserBookingsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUserBookingsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserBookingsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Bookings      []*Booking             `protobuf:"bytes,2,rep,name=bookings,proto3" json:"bookings,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBookingsResponse) Reset() {
	*x = GetUserBookingsResponse{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBookingsResponse) ProtoMessage() {}

func (x *GetUserBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBookingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserBookingsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserBookingsResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetUserBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetUserBookingsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateBookingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "confirmed", "active", "completed", "cancelled"
	UpdatedBy     uint32                 `protobuf:"varint,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusRequest) Reset() {
	*x = UpdateBookingStatusRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusRequest) ProtoMessage() {}

func (x *UpdateBookingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBookingStatusRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *UpdateBookingStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateBookingStatusRequest) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{8}
}

func (x *CancelBookingRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CancelBookingRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelBookingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CompleteBookingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BookingId      uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId         uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FinalMileage   float64                `protobuf:"fixed64,3,opt,name=final_mileage,json=finalMileage,proto3" json:"final_mileage,omitempty"`
	ConditionNotes string                 `protobuf:"bytes,4,opt,name=condition_notes,json=conditionNotes,proto3" json:"condition_notes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteBookingRequest) Reset() {
	*x = CompleteBookingRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBookingRequest) ProtoMessage() {}

func (x *CompleteBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBookingRequest.ProtoReflect.Descriptor instead.
func (*CompleteBookingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteBookingRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CompleteBookingRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompleteBookingRequest) GetFinalMileage() float64 {
	if x != nil {
		return x.FinalMileage
	}
	return 0
}

func (x *CompleteBookingRequest) GetConditionNotes() string {
	if x != nil {
		return x.ConditionNotes
	}
	return ""
}

// Payment Messages
type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // "razorpay", "stripe"
	PaymentType   string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`       // "deposit", "full", "additional_charges"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessPaymentRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessPaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Payment       *Payment               `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessPaymentResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ProcessPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PaymentId     uint32                 `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	RefundAmount  float64                `protobuf:"fixed64,3,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{12}
}

func (x *RefundPaymentRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *RefundPaymentRequest) GetPaymentId() uint32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *RefundPaymentRequest) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Damage Messages
type ReportDamageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Damages       []*DamageItem          `protobuf:"bytes,3,rep,name=damages,proto3" json:"damages,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDamageRequest) Reset() {
	*x = ReportDamageRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDamageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDamageRequest) ProtoMessage() {}

func (x *ReportDamageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDamageRequest.ProtoReflect.Descriptor instead.
func (*ReportDamageRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{13}
}

func (x *ReportDamageRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *ReportDamageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportDamageRequest) GetDamages() []*DamageItem {
	if x != nil {
		return x.Damages
	}
	return nil
}

func (x *ReportDamageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportDamageRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type GetDamageReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDamageReportsRequest) Reset() {
	*x = GetDamageReportsRequest{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDamageReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDamageReportsRequest) ProtoMessage() {}

func (x *GetDamageReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDamageReportsRequest.ProtoReflect.Descriptor instead.
func (*GetDamageReportsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{14}
}

func (x *GetDamageReportsRequest) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

type GetDamageReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reports       []*DamageReport        `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDamageReportsResponse) Reset() {
	*x = GetDamageReportsResponse{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDamageReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDamageReportsResponse) ProtoMessage() {}

func (x *GetDamageReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDamageReportsResponse.ProtoReflect.Descriptor instead.
func (*GetDamageReportsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{15}
}

func (x *GetDamageReportsResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetDamageReportsResponse) GetReports() []*DamageReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

// Data Models
type Booking struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BookingId          uint32                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId             uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VehicleId          uint32                 `protobuf:"varint,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	OfficeId           uint32                 `protobuf:"varint,4,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "pending", "confirmed", "active", "completed", "cancelled"
	PickupDate         string                 `protobuf:"bytes,6,opt,name=pickup_date,json=pickupDate,proto3" json:"pickup_date,omitempty"`
	ReturnDate         string                 `protobuf:"bytes,7,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	PickupTime         string                 `protobuf:"bytes,8,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	ReturnTime         string                 `protobuf:"bytes,9,opt,name=return_time,json=returnTime,proto3" json:"return_time,omitempty"`
	BaseAmount         float64                `protobuf:"fixed64,10,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	DepositAmount      float64                `protobuf:"fixed64,11,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
	TotalAmount        float64                `protobuf:"fixed64,12,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	AdditionalCharges  float64                `protobuf:"fixed64,13,opt,name=additional_charges,json=additionalCharges,proto3" json:"additional_charges,omitempty"`
	PaymentStatus      string                 `protobuf:"bytes,14,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	AdditionalServices []string               `protobuf:"bytes,15,rep,name=additional_services,json=additionalServices,proto3" json:"additional_services,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Vehicle            *Vehicle               `protobuf:"bytes,18,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Office             *Office                `protobuf:"bytes,19,opt,name=office,proto3" json:"office,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{16}
}

func (x *Booking) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Booking) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Booking) GetOfficeId() uint32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetPickupDate() string {
	if x != nil {
		return x.PickupDate
	}
	return ""
}

func (x *Booking) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *Booking) GetPickupTime() string {
	if x != nil {
		return x.PickupTime
	}
	return ""
}

func (x *Booking) GetReturnTime() string {
	if x != nil {
		return x.ReturnTime
	}
	return ""
}

func (x *Booking) GetBaseAmount() float64 {
	if x != nil {
		return x.BaseAmount
	}
	return 0
}

func (x *Booking) GetDepositAmount() float64 {
	if x != nil {
		return x.DepositAmount
	}
	return 0
}

func (x *Booking) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Booking) GetAdditionalCharges() float64 {
	if x != nil {
		return x.AdditionalCharges
	}
	return 0
}

func (x *Booking) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *Booking) GetAdditionalServices() []string {
	if x != nil {
		return x.AdditionalServices
	}
	return nil
}

func (x *Booking) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Booking) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Booking) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *Booking) GetOffice() *Office {
	if x != nil {
		return x.Office
	}
	return nil
}

type Vehicle struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VehicleId          uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "car", "bike"
	Transmission       string                 `protobuf:"bytes,4,opt,name=transmission,proto3" json:"transmission,omitempty"`
	FuelType           string                 `protobuf:"bytes,5,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,6,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	DailyRate          float64                `protobuf:"fixed64,7,opt,name=daily_rate,json=dailyRate,proto3" json:"daily_rate,omitempty"`
	HourlyRate         float64                `protobuf:"fixed64,8,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	Status             string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{17}
}

func (x *Vehicle) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Vehicle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vehicle) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Vehicle) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *Vehicle) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *Vehicle) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *Vehicle) GetDailyRate() float64 {
	if x != nil {
		return x.DailyRate
	}
	return 0
}

func (x *Vehicle) GetHourlyRate() float64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *Vehicle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Vehicle) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type Office struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfficeId      uint32                 `protobuf:"varint,1,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Zip           uint32                 `protobuf:"varint,6,opt,name=zip,proto3" json:"zip,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Latitude      float64                `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Office) Reset() {
	*x = Office{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Office) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Office) ProtoMessage() {}

func (x *Office) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Office.ProtoReflect.Descriptor instead.
func (*Office) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{18}
}

func (x *Office) GetOfficeId() uint32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *Office) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Office) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Office) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Office) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Office) GetZip() uint32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

func (x *Office) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Office) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Office) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint32                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	BookingId     uint32                 `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransactionId string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{19}
}

func (x *Payment) GetPaymentId() uint32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *Payment) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DamageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Part          string                 `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // "minor", "moderate", "severe"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	EstimatedCost float64                `protobuf:"fixed64,4,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DamageItem) Reset() {
	*x = DamageItem{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageItem) ProtoMessage() {}

func (x *DamageItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageItem.ProtoReflect.Descriptor instead.
func (*DamageItem) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{20}
}

func (x *DamageItem) GetPart() string {
	if x != nil {
		return x.Part
	}
	return ""
}

func (x *DamageItem) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *DamageItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DamageItem) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

type DamageReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      uint32                 `protobuf:"varint,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	BookingId     uint32                 `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Damages       []*DamageItem          `protobuf:"bytes,4,rep,name=damages,proto3" json:"damages,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,7,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "reported", "assessed", "approved", "paid"
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DamageReport) Reset() {
	*x = DamageReport{}
	mi := &file_internal_pb_booking_booking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageReport) ProtoMessage() {}

func (x *DamageReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_booking_booking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageReport.ProtoReflect.Descriptor instead.
func (*DamageReport) Descriptor() ([]byte, []int) {
	return file_internal_pb_booking_booking_proto_rawDescGZIP(), []int{21}
}

func (x *DamageReport) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *DamageReport) GetBookingId() uint32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *DamageReport) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DamageReport) GetDamages() []*DamageItem {
	if x != nil {
		return x.Damages
	}
	return nil
}

func (x *DamageReport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DamageReport) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *DamageReport) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *DamageReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DamageReport) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DamageReport) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_internal_pb_booking_booking_proto protoreflect.FileDescriptor

const file_internal_pb_booking_booking_proto_rawDesc = "" +
	"\n" +
	"!internal/pb/booking/booking.proto\x12\abooking\"\xac\x01\n" +
	"\bResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.booking.Response.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x12\x14\n" +
	"\x04data\x18\x04 \x01(\tH\x00R\x04data\"\x1b\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01B\t\n" +
	"\apayload\"\xa0\x02\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\rR\tvehicleId\x12\x1b\n" +
	"\toffice_id\x18\x03 \x01(\rR\bofficeId\x12\x1f\n" +
	"\vpickup_date\x18\x04 \x01(\tR\n" +
	"pickupDate\x12\x1f\n" +
	"\vreturn_date\x18\x05 \x01(\tR\n" +
	"returnDate\x12\x1f\n" +
	"\vpickup_time\x18\x06 \x01(\tR\n" +
	"pickupTime\x12\x1f\n" +
	"\vreturn_time\x18\a \x01(\tR\n" +
	"returnTime\x12/\n" +
	"\x13additional_services\x18\b \x03(\tR\x12additionalServices\"\x93\x01\n" +
	"\x15CreateBookingResponse\x12-\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.booking.ResponseR\bresponse\x12*\n" +
	"\abooking\x18\x02 \x01(\v2\x10.booking.BookingR\abooking\x12\x1f\n" +
	"\vpayment_url\x18\x03 \x01(\tR\n" +
	"paymentUrl\"K\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"o\n" +
	"\x12GetBookingResponse\x12-\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.booking.ResponseR\bresponse\x12*\n" +
	"\abooking\x18\x02 \x01(\v2\x10.booking.BookingR\abooking\"w\n" +
	"\x16GetUserBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"\x97\x01\n" +
	"\x17GetUserBookingsResponse\x12-\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.booking.ResponseR\bresponse\x12,\n" +
	"\bbookings\x18\x02 \x03(\v2\x10.booking.BookingR\bbookings\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"r\n" +
	"\x1aUpdateBookingStatusRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\rR\tupdatedBy\"f\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9e\x01\n" +
	"\x16CompleteBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12#\n" +
	"\rfinal_mileage\x18\x03 \x01(\x01R\ffinalMileage\x12'\n" +
	"\x0fcondition_notes\x18\x04 \x01(\tR\x0econditionNotes\"\x98\x01\n" +
	"\x15ProcessPaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\"s\n" +
	"\x16ProcessPaymentResponse\x12-\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.booking.ResponseR\bresponse\x12*\n" +
	"\apayment\x18\x02 \x01(\v2\x10.booking.PaymentR\apayment\"\x91\x01\n" +
	"\x14RefundPaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\rR\tpaymentId\x12#\n" +
	"\rrefund_amount\x18\x03 \x01(\x01R\frefundAmount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xb6\x01\n" +
	"\x13ReportDamageRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12-\n" +
	"\adamages\x18\x03 \x03(\v2\x13.booking.DamageItemR\adamages\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\"8\n" +
	"\x17GetDamageReportsRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\"z\n" +
	"\x18GetDamageReportsResponse\x12-\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.booking.ResponseR\bresponse\x12/\n" +
	"\areports\x18\x02 \x03(\v2\x15.booking.DamageReportR\areports\"\x9e\x05\n" +
	"\aBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\rR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\rR\tvehicleId\x12\x1b\n" +
	"\toffice_id\x18\x04 \x01(\rR\bofficeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vpickup_date\x18\x06 \x01(\tR\n" +
	"pickupDate\x12\x1f\n" +
	"\vreturn_date\x18\a \x01(\tR\n" +
	"returnDate\x12\x1f\n" +
	"\vpickup_time\x18\b \x01(\tR\n" +
	"pickupTime\x12\x1f\n" +
	"\vreturn_time\x18\t \x01(\tR\n" +
	"returnTime\x12\x1f\n" +
	"\vbase_amount\x18\n" +
	" \x01(\x01R\n" +
	"baseAmount\x12%\n" +
	"\x0edeposit_amount\x18\v \x01(\x01R\rdepositAmount\x12!\n" +
	"\ftotal_amount\x18\f \x01(\x01R\vtotalAmount\x12-\n" +
	"\x12additional_charges\x18\r \x01(\x01R\x11additionalCharges\x12%\n" +
	"\x0epayment_status\x18\x0e \x01(\tR\rpaymentStatus\x12/\n" +
	"\x13additional_services\x18\x0f \x03(\tR\x12additionalServices\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\x12*\n" +
	"\avehicle\x18\x12 \x01(\v2\x10.booking.VehicleR\avehicle\x12'\n" +
	"\x06office\x18\x13 \x01(\v2\x0f.booking.OfficeR\x06office\"\xb7\x02\n" +
	"\aVehicle\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\"\n" +
	"\ftransmission\x18\x04 \x01(\tR\ftransmission\x12\x1b\n" +
	"\tfuel_type\x18\x05 \x01(\tR\bfuelType\x12/\n" +
	"\x13registration_number\x18\x06 \x01(\tR\x12registrationNumber\x12\x1d\n" +
	"\n" +
	"daily_rate\x18\a \x01(\x01R\tdailyRate\x12\x1f\n" +
	"\vhourly_rate\x18\b \x01(\x01R\n" +
	"hourlyRate\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\"\xdf\x01\n" +
	"\x06Office\x12\x1b\n" +
	"\toffice_id\x18\x01 \x01(\rR\bofficeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x06 \x01(\rR\x03zip\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x01R\tlongitude\"\x80\x02\n" +
	"\aPayment\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\rR\tpaymentId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\rR\tbookingId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x85\x01\n" +
	"\n" +
	"DamageItem\x12\x12\n" +
	"\x04part\x18\x01 \x01(\tR\x04part\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0eestimated_cost\x18\x04 \x01(\x01R\restimatedCost\"\xc1\x02\n" +
	"\fDamageReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\rR\breportId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\rR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12-\n" +
	"\adamages\x18\x04 \x03(\v2\x13.booking.DamageItemR\adamages\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x12\x1d\n" +
	"\n" +
	"total_cost\x18\a \x01(\x01R\ttotalCost\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt2\x86\x06\n" +
	"\x0eBookingService\x12N\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x1e.booking.CreateBookingResponse\x12E\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x1b.booking.GetBookingResponse\x12T\n" +
	"\x0fGetUserBookings\x12\x1f.booking.GetUserBookingsRequest\x1a .booking.GetUserBookingsResponse\x12M\n" +
	"\x13UpdateBookingStatus\x12#.booking.UpdateBookingStatusRequest\x1a\x11.booking.Response\x12A\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x11.booking.Response\x12E\n" +
	"\x0fCompleteBooking\x12\x1f.booking.CompleteBookingRequest\x1a\x11.booking.Response\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.booking.ProcessPaymentRequest\x1a\x1f.booking.ProcessPaymentResponse\x12A\n" +
	"\rRefundPayment\x12\x1d.booking.RefundPaymentRequest\x1a\x11.booking.Response\x12?\n" +
	"\fReportDamage\x12\x1c.booking.ReportDamageRequest\x1a\x11.booking.Response\x12W\n" +
	"\x10GetDamageReports\x12 .booking.GetDamageReportsRequest\x1a!.booking.GetDamageReportsResponseBUZSgithub.com/yourorg/ultimate-rent-car/ultimate-rent-user-service/internal/pb/bookingb\x06proto3"

var (
	file_internal_pb_booking_booking_proto_rawDescOnce sync.Once
	file_internal_pb_booking_booking_proto_rawDescData []byte
)

func file_internal_pb_booking_booking_proto_rawDescGZIP() []byte {
	file_internal_pb_booking_booking_proto_rawDescOnce.Do(func() {
		file_internal_pb_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_booking_booking_proto_rawDesc), len(file_internal_pb_booking_booking_proto_rawDesc)))
	})
	return file_internal_pb_booking_booking_proto_rawDescData
}

var file_internal_pb_booking_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_pb_booking_booking_proto_goTypes = []any{
	(Response_Status)(0),               // 0: booking.Response.Status
	(*Response)(nil),                   // 1: booking.Response
	(*CreateBookingRequest)(nil),       // 2: booking.CreateBookingRequest
	(*CreateBookingResponse)(nil),      // 3: booking.CreateBookingResponse
	(*GetBookingRequest)(nil),          // 4: booking.GetBookingRequest
	(*GetBookingResponse)(nil),         // 5: booking.GetBookingResponse
	(*GetUserBookingsRequest)(nil),     // 6: booking.GetUserBookingsRequest
	(*GetUserBookingsResponse)(nil),    // 7: booking.GetUserBookingsResponse
	(*UpdateBookingStatusRequest)(nil), // 8: booking.UpdateBookingStatusRequest
	(*CancelBookingRequest)(nil),       // 9: booking.CancelBookingRequest
	(*CompleteBookingRequest)(nil),     // 10: booking.CompleteBookingRequest
	(*ProcessPaymentRequest)(nil),      // 11: booking.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),     // 12: booking.ProcessPaymentResponse
	(*RefundPaymentRequest)(nil),       // 13: booking.RefundPaymentRequest
	(*ReportDamageRequest)(nil),        // 14: booking.ReportDamageRequest
	(*GetDamageReportsRequest)(nil),    // 15: booking.GetDamageReportsRequest
	(*GetDamageReportsResponse)(nil),   // 16: booking.GetDamageReportsResponse
	(*Booking)(nil),                    // 17: booking.Booking
	(*Vehicle)(nil),                    // 18: booking.Vehicle
	(*Office)(nil),                     // 19: booking.Office
	(*Payment)(nil),                    // 20: booking.Payment
	(*DamageItem)(nil),                 // 21: booking.DamageItem
	(*DamageReport)(nil),               // 22: booking.DamageReport
}
var file_internal_pb_booking_booking_proto_depIdxs = []int32{
	0,  // 0: booking.Response.status:type_name -> booking.Response.Status
	1,  // 1: booking.CreateBookingResponse.response:type_name -> booking.Response
	17, // 2: booking.CreateBookingResponse.booking:type_name -> booking.Booking
	1,  // 3: booking.GetBookingResponse.response:type_name -> booking.Response
	17, // 4: booking.GetBookingResponse.booking:type_name -> booking.Booking
	1,  // 5: booking.GetUserBookingsResponse.response:type_name -> booking.Response
	17, // 6: booking.GetUserBookingsResponse.bookings:type_name -> booking.Booking
	1,  // 7: booking.ProcessPaymentResponse.response:type_name -> booking.Response
	20, // 8: booking.ProcessPaymentResponse.payment:type_name -> booking.Payment
	21, // 9: booking.ReportDamageRequest.damages:type_name -> booking.DamageItem
	1,  // 10: booking.GetDamageReportsResponse.response:type_name -> booking.Response
	22, // 11: booking.GetDamageReportsResponse.reports:type_name -> booking.DamageReport
	18, // 12: booking.Booking.vehicle:type_name -> booking.Vehicle
	19, // 13: booking.Booking.office:type_name -> booking.Office
	21, // 14: booking.DamageReport.damages:type_name -> booking.DamageItem
	2,  // 15: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	4,  // 16: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	6,  // 17: booking.BookingService.GetUserBookings:input_type -> booking.GetUserBookingsRequest
	8,  // 18: booking.BookingService.UpdateBookingStatus:input_type -> booking.UpdateBookingStatusRequest
	9,  // 19: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	10, // 20: booking.BookingService.CompleteBooking:input_type -> booking.CompleteBookingRequest
	11, // 21: booking.BookingService.ProcessPayment:input_type -> booking.ProcessPaymentRequest
	13, // 22: booking.BookingService.RefundPayment:input_type -> booking.RefundPaymentRequest
	14, // 23: booking.BookingService.ReportDamage:input_type -> booking.ReportDamageRequest
	15, // 24: booking.BookingService.GetDamageReports:input_type -> booking.GetDamageReportsRequest
	3,  // 25: booking.BookingService.CreateBooking:output_type -> booking.CreateBookingResponse
	5,  // 26: booking.BookingService.GetBooking:output_type -> booking.GetBookingResponse
	7,  // 27: booking.BookingService.GetUserBookings:output_type -> booking.GetUserBookingsResponse
	1,  // 28: booking.BookingService.UpdateBookingStatus:output_type -> booking.Response
	1,  // 29: booking.BookingService.CancelBooking:output_type -> booking.Response
	1,  // 30: booking.BookingService.CompleteBooking:output_type -> booking.Response
	12, // 31: booking.BookingService.ProcessPayment:output_type -> booking.ProcessPaymentResponse
	1,  // 32: booking.BookingService.RefundPayment:output_type -> booking.Response
	1,  // 33: booking.BookingService.ReportDamage:output_type -> booking.Response
	16, // 34: booking.BookingService.GetDamageReports:output_type -> booking.GetDamageReportsResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_pb_booking_booking_proto_init() }
func file_internal_pb_booking_booking_proto_init() {
	if File_internal_pb_booking_booking_proto != nil {
		return
	}
	file_internal_pb_booking_booking_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_Error)(nil),
		(*Response_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_booking_booking_proto_rawDesc), len(file_internal_pb_booking_booking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_booking_booking_proto_goTypes,
		DependencyIndexes: file_internal_pb_booking_booking_proto_depIdxs,
		EnumInfos:         file_internal_pb_booking_booking_proto_enumTypes,
		MessageInfos:      file_internal_pb_booking_booking_proto_msgTypes,
	}.Build()
	File_internal_pb_booking_booking_proto = out.File
	file_internal_pb_booking_booking_proto_goTypes = nil
	file_internal_pb_booking_booking_proto_depIdxs = nil
}
