// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/pb/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_Status int32

const (
	Response_OK    Response_Status = 0
	Response_ERROR Response_Status = 1
)

// Enum value maps for Response_Status.
var (
	Response_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Response_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}

func (x Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_notification_notification_proto_enumTypes[0].Descriptor()
}

func (Response_Status) Type() protoreflect.EnumType {
	return &file_internal_pb_notification_notification_proto_enumTypes[0]
}

func (x Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Status.Descriptor instead.
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{0, 0}
}

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  Response_Status        `protobuf:"varint,1,opt,name=status,proto3,enum=notification.Response_Status" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Error
	//	*Response_Data
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetStatus() Response_Status {
	if x != nil {
		return x.Status
	}
	return Response_OK
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Data); ok {
			return x.Data
		}
	}
	return ""
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Response_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*Response_Error) isResponse_Payload() {}

func (*Response_Data) isResponse_Payload() {}

// SMS Messages
type SendSMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateData  map[string]string      `protobuf:"bytes,4,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // 1=low, 2=normal, 3=high
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSRequest) Reset() {
	*x = SendSMSRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSRequest) ProtoMessage() {}

func (x *SendSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSRequest.ProtoReflect.Descriptor instead.
func (*SendSMSRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendSMSRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSMSRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendSMSRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendSMSRequest) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *SendSMSRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SendBulkSMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SendSMSRequest      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkSMSRequest) Reset() {
	*x = SendBulkSMSRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkSMSRequest) ProtoMessage() {}

func (x *SendBulkSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkSMSRequest.ProtoReflect.Descriptor instead.
func (*SendBulkSMSRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendBulkSMSRequest) GetMessages() []*SendSMSRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Email Messages
type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToEmail       string                 `protobuf:"bytes,1,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateData  map[string]string      `protobuf:"bytes,5,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cc            []string               `protobuf:"bytes,6,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,7,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,8,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Priority      uint32                 `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendEmailRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *SendEmailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendEmailRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SendBulkEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*SendEmailRequest    `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkEmailRequest) Reset() {
	*x = SendBulkEmailRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailRequest) ProtoMessage() {}

func (x *SendBulkEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailRequest.ProtoReflect.Descriptor instead.
func (*SendBulkEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SendBulkEmailRequest) GetEmails() []*SendEmailRequest {
	if x != nil {
		return x.Emails
	}
	return nil
}

// Push Notification Messages
type SendPushNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON string for additional data
	DeviceToken   string                 `protobuf:"bytes,5,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Priority      uint32                 `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPushNotificationRequest) Reset() {
	*x = SendPushNotificationRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPushNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPushNotificationRequest) ProtoMessage() {}

func (x *SendPushNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPushNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendPushNotificationRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SendPushNotificationRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendPushNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendPushNotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendPushNotificationRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SendPushNotificationRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *SendPushNotificationRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SendBulkPushNotificationRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Notifications []*SendPushNotificationRequest `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkPushNotificationRequest) Reset() {
	*x = SendBulkPushNotificationRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkPushNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkPushNotificationRequest) ProtoMessage() {}

func (x *SendBulkPushNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkPushNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendBulkPushNotificationRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *SendBulkPushNotificationRequest) GetNotifications() []*SendPushNotificationRequest {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// WhatsApp Messages
type SendWhatsAppMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateData  map[string]string      `protobuf:"bytes,4,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Media         []*MediaAttachment     `protobuf:"bytes,5,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWhatsAppMessageRequest) Reset() {
	*x = SendWhatsAppMessageRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWhatsAppMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWhatsAppMessageRequest) ProtoMessage() {}

func (x *SendWhatsAppMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWhatsAppMessageRequest.ProtoReflect.Descriptor instead.
func (*SendWhatsAppMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *SendWhatsAppMessageRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendWhatsAppMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendWhatsAppMessageRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendWhatsAppMessageRequest) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *SendWhatsAppMessageRequest) GetMedia() []*MediaAttachment {
	if x != nil {
		return x.Media
	}
	return nil
}

// Template Messages
type GetNotificationTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // "sms", "email", "whatsapp", "push"
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // "booking", "payment", "reminder", etc.
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationTemplatesRequest) Reset() {
	*x = GetNotificationTemplatesRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationTemplatesRequest) ProtoMessage() {}

func (x *GetNotificationTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetNotificationTemplatesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetNotificationTemplatesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetNotificationTemplatesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationTemplatesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetNotificationTemplatesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Response      *Response               `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Templates     []*NotificationTemplate `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	TotalCount    uint32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationTemplatesResponse) Reset() {
	*x = GetNotificationTemplatesResponse{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationTemplatesResponse) ProtoMessage() {}

func (x *GetNotificationTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *GetNotificationTemplatesResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetNotificationTemplatesResponse) GetTemplates() []*NotificationTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *GetNotificationTemplatesResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateNotificationTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"` // for email
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Variables     []string               `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationTemplateRequest) Reset() {
	*x = CreateNotificationTemplateRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationTemplateRequest) ProtoMessage() {}

func (x *CreateNotificationTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationTemplateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNotificationTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNotificationTemplateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNotificationTemplateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateNotificationTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateNotificationTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNotificationTemplateRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *CreateNotificationTemplateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateNotificationTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Variables     []string               `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationTemplateRequest) Reset() {
	*x = UpdateNotificationTemplateRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationTemplateRequest) ProtoMessage() {}

func (x *UpdateNotificationTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationTemplateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNotificationTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UpdateNotificationTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNotificationTemplateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateNotificationTemplateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateNotificationTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UpdateNotificationTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateNotificationTemplateRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *UpdateNotificationTemplateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// History Messages
type GetNotificationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Limit         uint32                 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryRequest) Reset() {
	*x = GetNotificationHistoryRequest{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryRequest) ProtoMessage() {}

func (x *GetNotificationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{12}
}

func (x *GetNotificationHistoryRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNotificationHistoryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetNotificationHistoryRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNotificationHistoryRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetNotificationHistoryRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetNotificationHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationHistoryRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetNotificationHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	History       []*NotificationHistory `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryResponse) Reset() {
	*x = GetNotificationHistoryResponse{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryResponse) ProtoMessage() {}

func (x *GetNotificationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{13}
}

func (x *GetNotificationHistoryResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetNotificationHistoryResponse) GetHistory() []*NotificationHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetNotificationHistoryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Data Models
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{14}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type MediaAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "image", "video", "document"
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAttachment) Reset() {
	*x = MediaAttachment{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAttachment) ProtoMessage() {}

func (x *MediaAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAttachment.ProtoReflect.Descriptor instead.
func (*MediaAttachment) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{15}
}

func (x *MediaAttachment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaAttachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaAttachment) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type NotificationTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Variables     []string               `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTemplate) Reset() {
	*x = NotificationTemplate{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTemplate) ProtoMessage() {}

func (x *NotificationTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTemplate.ProtoReflect.Descriptor instead.
func (*NotificationTemplate) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{16}
}

func (x *NotificationTemplate) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *NotificationTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotificationTemplate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationTemplate) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NotificationTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationTemplate) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *NotificationTemplate) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *NotificationTemplate) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NotificationTemplate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type NotificationHistory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationId   string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId           uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`           // "sms", "email", "push", "whatsapp"
	Recipient        string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"` // phone/email/device_token
	Subject          string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Content          string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "sent", "delivered", "failed", "pending"
	ProviderResponse string                 `protobuf:"bytes,8,opt,name=provider_response,json=providerResponse,proto3" json:"provider_response,omitempty"`
	SentAt           string                 `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	DeliveredAt      string                 `protobuf:"bytes,10,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationHistory) Reset() {
	*x = NotificationHistory{}
	mi := &file_internal_pb_notification_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationHistory) ProtoMessage() {}

func (x *NotificationHistory) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_notification_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationHistory.ProtoReflect.Descriptor instead.
func (*NotificationHistory) Descriptor() ([]byte, []int) {
	return file_internal_pb_notification_notification_proto_rawDescGZIP(), []int{17}
}

func (x *NotificationHistory) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationHistory) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationHistory) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationHistory) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *NotificationHistory) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationHistory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationHistory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationHistory) GetProviderResponse() string {
	if x != nil {
		return x.ProviderResponse
	}
	return ""
}

func (x *NotificationHistory) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *NotificationHistory) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

func (x *NotificationHistory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_internal_pb_notification_notification_proto protoreflect.FileDescriptor

const file_internal_pb_notification_notification_proto_rawDesc = "" +
	"\n" +
	"+internal/pb/notification/notification.proto\x12\fnotification\"\xb1\x01\n" +
	"\bResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.notification.Response.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x12\x14\n" +
	"\x04data\x18\x04 \x01(\tH\x00R\x04data\"\x1b\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01B\t\n" +
	"\apayload\"\x93\x02\n" +
	"\x0eSendSMSRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12S\n" +
	"\rtemplate_data\x18\x04 \x03(\v2..notification.SendSMSRequest.TemplateDataEntryR\ftemplateData\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x12SendBulkSMSRequest\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.notification.SendSMSRequestR\bmessages\"\x8e\x03\n" +
	"\x10SendEmailRequest\x12\x19\n" +
	"\bto_email\x18\x01 \x01(\tR\atoEmail\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12U\n" +
	"\rtemplate_data\x18\x05 \x03(\v20.notification.SendEmailRequest.TemplateDataEntryR\ftemplateData\x12\x0e\n" +
	"\x02cc\x18\x06 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\a \x03(\tR\x03bcc\x12:\n" +
	"\vattachments\x18\b \x03(\v2\x18.notification.AttachmentR\vattachments\x12\x1a\n" +
	"\bpriority\x18\t \x01(\rR\bpriority\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x14SendBulkEmailRequest\x126\n" +
	"\x06emails\x18\x01 \x03(\v2\x1e.notification.SendEmailRequestR\x06emails\"\xb3\x01\n" +
	"\x1bSendPushNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12!\n" +
	"\fdevice_token\x18\x05 \x01(\tR\vdeviceToken\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\rR\bpriority\"r\n" +
	"\x1fSendBulkPushNotificationRequest\x12O\n" +
	"\rnotifications\x18\x01 \x03(\v2).notification.SendPushNotificationRequestR\rnotifications\"\xc4\x02\n" +
	"\x1aSendWhatsAppMessageRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12_\n" +
	"\rtemplate_data\x18\x04 \x03(\v2:.notification.SendWhatsAppMessageRequest.TemplateDataEntryR\ftemplateData\x123\n" +
	"\x05media\x18\x05 \x03(\v2\x1d.notification.MediaAttachmentR\x05media\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x1fGetNotificationTemplatesRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"\xb9\x01\n" +
	" GetNotificationTemplatesResponse\x122\n" +
	"\bresponse\x18\x01 \x01(\v2\x16.notification.ResponseR\bresponse\x12@\n" +
	"\ttemplates\x18\x02 \x03(\v2\".notification.NotificationTemplateR\ttemplates\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"\xd6\x01\n" +
	"!CreateNotificationTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\tvariables\x18\x06 \x03(\tR\tvariables\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\xf7\x01\n" +
	"!UpdateNotificationTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1c\n" +
	"\tvariables\x18\a \x03(\tR\tvariables\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"\xcc\x01\n" +
	"\x1dGetNotificationHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\rR\x06offset\"\xb2\x01\n" +
	"\x1eGetNotificationHistoryResponse\x122\n" +
	"\bresponse\x18\x01 \x01(\v2\x16.notification.ResponseR\bresponse\x12;\n" +
	"\ahistory\x18\x02 \x03(\v2!.notification.NotificationHistoryR\ahistory\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"_\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"Q\n" +
	"\x0fMediaAttachment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\"\xa8\x02\n" +
	"\x14NotificationTemplate\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1c\n" +
	"\tvariables\x18\a \x03(\tR\tvariables\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xdd\x02\n" +
	"\x13NotificationHistory\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12+\n" +
	"\x11provider_response\x18\b \x01(\tR\x10providerResponse\x12\x17\n" +
	"\asent_at\x18\t \x01(\tR\x06sentAt\x12!\n" +
	"\fdelivered_at\x18\n" +
	" \x01(\tR\vdeliveredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt2\x86\b\n" +
	"\x13NotificationService\x12?\n" +
	"\aSendSMS\x12\x1c.notification.SendSMSRequest\x1a\x16.notification.Response\x12G\n" +
	"\vSendBulkSMS\x12 .notification.SendBulkSMSRequest\x1a\x16.notification.Response\x12C\n" +
	"\tSendEmail\x12\x1e.notification.SendEmailRequest\x1a\x16.notification.Response\x12K\n" +
	"\rSendBulkEmail\x12\".notification.SendBulkEmailRequest\x1a\x16.notification.Response\x12Y\n" +
	"\x14SendPushNotification\x12).notification.SendPushNotificationRequest\x1a\x16.notification.Response\x12a\n" +
	"\x18SendBulkPushNotification\x12-.notification.SendBulkPushNotificationRequest\x1a\x16.notification.Response\x12W\n" +
	"\x13SendWhatsAppMessage\x12(.notification.SendWhatsAppMessageRequest\x1a\x16.notification.Response\x12y\n" +
	"\x18GetNotificationTemplates\x12-.notification.GetNotificationTemplatesRequest\x1a..notification.GetNotificationTemplatesResponse\x12e\n" +
	"\x1aCreateNotificationTemplate\x12/.notification.CreateNotificationTemplateRequest\x1a\x16.notification.Response\x12e\n" +
	"\x1aUpdateNotificationTemplate\x12/.notification.UpdateNotificationTemplateRequest\x1a\x16.notification.Response\x12s\n" +
	"\x16GetNotificationHistory\x12+.notification.GetNotificationHistoryRequest\x1a,.notification.GetNotificationHistoryResponseBZZXgithub.com/yourorg/ultimate-rent-car/ultimate-rent-user-service/internal/pb/notificationb\x06proto3"

var (
	file_internal_pb_notification_notification_proto_rawDescOnce sync.Once
	file_internal_pb_notification_notification_proto_rawDescData []byte
)

func file_internal_pb_notification_notification_proto_rawDescGZIP() []byte {
	file_internal_pb_notification_notification_proto_rawDescOnce.Do(func() {
		file_internal_pb_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_notification_notification_proto_rawDesc), len(file_internal_pb_notification_notification_proto_rawDesc)))
	})
	return file_internal_pb_notification_notification_proto_rawDescData
}

var file_internal_pb_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_pb_notification_notification_proto_goTypes = []any{
	(Response_Status)(0),                      // 0: notification.Response.Status
	(*Response)(nil),                          // 1: notification.Response
	(*SendSMSRequest)(nil),                    // 2: notification.SendSMSRequest
	(*SendBulkSMSRequest)(nil),                // 3: notification.SendBulkSMSRequest
	(*SendEmailRequest)(nil),                  // 4: notification.SendEmailRequest
	(*SendBulkEmailRequest)(nil),              // 5: notification.SendBulkEmailRequest
	(*SendPushNotificationRequest)(nil),       // 6: notification.SendPushNotificationRequest
	(*SendBulkPushNotificationRequest)(nil),   // 7: notification.SendBulkPushNotificationRequest
	(*SendWhatsAppMessageRequest)(nil),        // 8: notification.SendWhatsAppMessageRequest
	(*GetNotificationTemplatesRequest)(nil),   // 9: notification.GetNotificationTemplatesRequest
	(*GetNotificationTemplatesResponse)(nil),  // 10: notification.GetNotificationTemplatesResponse
	(*CreateNotificationTemplateRequest)(nil), // 11: notification.CreateNotificationTemplateRequest
	(*UpdateNotificationTemplateRequest)(nil), // 12: notification.UpdateNotificationTemplateRequest
	(*GetNotificationHistoryRequest)(nil),     // 13: notification.GetNotificationHistoryRequest
	(*GetNotificationHistoryResponse)(nil),    // 14: notification.GetNotificationHistoryResponse
	(*Attachment)(nil),                        // 15: notification.Attachment
	(*MediaAttachment)(nil),                   // 16: notification.MediaAttachment
	(*NotificationTemplate)(nil),              // 17: notification.NotificationTemplate
	(*NotificationHistory)(nil),               // 18: notification.NotificationHistory
	nil,                                       // 19: notification.SendSMSRequest.TemplateDataEntry
	nil,                                       // 20: notification.SendEmailRequest.TemplateDataEntry
	nil,                                       // 21: notification.SendWhatsAppMessageRequest.TemplateDataEntry
}
var file_internal_pb_notification_notification_proto_depIdxs = []int32{
	0,  // 0: notification.Response.status:type_name -> notification.Response.Status
	19, // 1: notification.SendSMSRequest.template_data:type_name -> notification.SendSMSRequest.TemplateDataEntry
	2,  // 2: notification.SendBulkSMSRequest.messages:type_name -> notification.SendSMSRequest
	20, // 3: notification.SendEmailRequest.template_data:type_name -> notification.SendEmailRequest.TemplateDataEntry
	15, // 4: notification.SendEmailRequest.attachments:type_name -> notification.Attachment
	4,  // 5: notification.SendBulkEmailRequest.emails:type_name -> notification.SendEmailRequest
	6,  // 6: notification.SendBulkPushNotificationRequest.notifications:type_name -> notification.SendPushNotificationRequest
	21, // 7: notification.SendWhatsAppMessageRequest.template_data:type_name -> notification.SendWhatsAppMessageRequest.TemplateDataEntry
	16, // 8: notification.SendWhatsAppMessageRequest.media:type_name -> notification.MediaAttachment
	1,  // 9: notification.GetNotificationTemplatesResponse.response:type_name -> notification.Response
	17, // 10: notification.GetNotificationTemplatesResponse.templates:type_name -> notification.NotificationTemplate
	1,  // 11: notification.GetNotificationHistoryResponse.response:type_name -> notification.Response
	18, // 12: notification.GetNotificationHistoryResponse.history:type_name -> notification.NotificationHistory
	2,  // 13: notification.NotificationService.SendSMS:input_type -> notification.SendSMSRequest
	3,  // 14: notification.NotificationService.SendBulkSMS:input_type -> notification.SendBulkSMSRequest
	4,  // 15: notification.NotificationService.SendEmail:input_type -> notification.SendEmailRequest
	5,  // 16: notification.NotificationService.SendBulkEmail:input_type -> notification.SendBulkEmailRequest
	6,  // 17: notification.NotificationService.SendPushNotification:input_type -> notification.SendPushNotificationRequest
	7,  // 18: notification.NotificationService.SendBulkPushNotification:input_type -> notification.SendBulkPushNotificationRequest
	8,  // 19: notification.NotificationService.SendWhatsAppMessage:input_type -> notification.SendWhatsAppMessageRequest
	9,  // 20: notification.NotificationService.GetNotificationTemplates:input_type -> notification.GetNotificationTemplatesRequest
	11, // 21: notification.NotificationService.CreateNotificationTemplate:input_type -> notification.CreateNotificationTemplateRequest
	12, // 22: notification.NotificationService.UpdateNotificationTemplate:input_type -> notification.UpdateNotificationTemplateRequest
	13, // 23: notification.NotificationService.GetNotificationHistory:input_type -> notification.GetNotificationHistoryRequest
	1,  // 24: notification.NotificationService.SendSMS:output_type -> notification.Response
	1,  // 25: notification.NotificationService.SendBulkSMS:output_type -> notification.Response
	1,  // 26: notification.NotificationService.SendEmail:output_type -> notification.Response
	1,  // 27: notification.NotificationService.SendBulkEmail:output_type -> notification.Response
	1,  // 28: notification.NotificationService.SendPushNotification:output_type -> notification.Response
	1,  // 29: notification.NotificationService.SendBulkPushNotification:output_type -> notification.Response
	1,  // 30: notification.NotificationService.SendWhatsAppMessage:output_type -> notification.Response
	10, // 31: notification.NotificationService.GetNotificationTemplates:output_type -> notification.GetNotificationTemplatesResponse
	1,  // 32: notification.NotificationService.CreateNotificationTemplate:output_type -> notification.Response
	1,  // 33: notification.NotificationService.UpdateNotificationTemplate:output_type -> notification.Response
	14, // 34: notification.NotificationService.GetNotificationHistory:output_type -> notification.GetNotificationHistoryResponse
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_pb_notification_notification_proto_init() }
func file_internal_pb_notification_notification_proto_init() {
	if File_internal_pb_notification_notification_proto != nil {
		return
	}
	file_internal_pb_notification_notification_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_Error)(nil),
		(*Response_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_notification_notification_proto_rawDesc), len(file_internal_pb_notification_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_notification_notification_proto_goTypes,
		DependencyIndexes: file_internal_pb_notification_notification_proto_depIdxs,
		EnumInfos:         file_internal_pb_notification_notification_proto_enumTypes,
		MessageInfos:      file_internal_pb_notification_notification_proto_msgTypes,
	}.Build()
	File_internal_pb_notification_notification_proto = out.File
	file_internal_pb_notification_notification_proto_goTypes = nil
	file_internal_pb_notification_notification_proto_depIdxs = nil
}
