// By Ratheesh Kumar, Back-end Engineer
// Last update: [Current Date]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/pb/ulimateuser/user.proto

package ulimateuser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_Status int32

const (
	Response_OK    Response_Status = 0
	Response_ERROR Response_Status = 1
)

// Enum value maps for Response_Status.
var (
	Response_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Response_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}

func (x Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_ulimateuser_user_proto_enumTypes[0].Descriptor()
}

func (Response_Status) Type() protoreflect.EnumType {
	return &file_internal_pb_ulimateuser_user_proto_enumTypes[0]
}

func (x Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Status.Descriptor instead.
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{1, 0}
}

type NoParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  Response_Status        `protobuf:"varint,1,opt,name=status,proto3,enum=ulimateuser.Response_Status" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Error
	//	*Response_Data
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() Response_Status {
	if x != nil {
		return x.Status
	}
	return Response_OK
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Data); ok {
			return x.Data
		}
	}
	return ""
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Response_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*Response_Error) isResponse_Payload() {}

func (*Response_Data) isResponse_Payload() {}

// User Authentication Messages
type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{2}
}

func (x *SignupRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SignupRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{3}
}

func (x *SignupResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SignupResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpRequest) Reset() {
	*x = OtpRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpRequest) ProtoMessage() {}

func (x *OtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpRequest.ProtoReflect.Descriptor instead.
func (*OtpRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{4}
}

func (x *OtpRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Profile Messages
type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Profile       *Profile               `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{7}
}

func (x *ProfileResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AadharNo      string                 `protobuf:"bytes,5,opt,name=aadhar_no,json=aadharNo,proto3" json:"aadhar_no,omitempty"`
	PancardNo     string                 `protobuf:"bytes,6,opt,name=pancard_no,json=pancardNo,proto3" json:"pancard_no,omitempty"`
	Licence       string                 `protobuf:"bytes,7,opt,name=licence,proto3" json:"licence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetAadharNo() string {
	if x != nil {
		return x.AadharNo
	}
	return ""
}

func (x *UpdateProfileRequest) GetPancardNo() string {
	if x != nil {
		return x.PancardNo
	}
	return ""
}

func (x *UpdateProfileRequest) GetLicence() string {
	if x != nil {
		return x.Licence
	}
	return ""
}

// Address Messages
type AddAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	House         string                 `protobuf:"bytes,2,opt,name=house,proto3" json:"house,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Zip           uint32                 `protobuf:"varint,5,opt,name=zip,proto3" json:"zip,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddressRequest) Reset() {
	*x = AddAddressRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressRequest) ProtoMessage() {}

func (x *AddAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressRequest.ProtoReflect.Descriptor instead.
func (*AddAddressRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{9}
}

func (x *AddAddressRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddAddressRequest) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *AddAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *AddAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddAddressRequest) GetZip() uint32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

func (x *AddAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	House         string                 `protobuf:"bytes,3,opt,name=house,proto3" json:"house,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Zip           uint32                 `protobuf:"varint,6,opt,name=zip,proto3" json:"zip,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAddressRequest) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *UpdateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateAddressRequest) GetZip() uint32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

func (x *UpdateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type AddressListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListResponse) Reset() {
	*x = AddressListResponse{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListResponse) ProtoMessage() {}

func (x *AddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListResponse.ProtoReflect.Descriptor instead.
func (*AddressListResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{11}
}

func (x *AddressListResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AddressListResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Password Messages
type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword     string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,4,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{12}
}

func (x *ChangePasswordRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

// Document Upload Messages
type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"` // "aadhar", "pancard", "licence"
	DocumentData  []byte                 `protobuf:"bytes,3,opt,name=document_data,json=documentData,proto3" json:"document_data,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{13}
}

func (x *UploadDocumentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *UploadDocumentRequest) GetDocumentData() []byte {
	if x != nil {
		return x.DocumentData
	}
	return nil
}

func (x *UploadDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// Wallet Messages
type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Balance       float32                `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{14}
}

func (x *WalletResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *WalletResponse) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type UpdateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "credit", "debit"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletRequest) Reset() {
	*x = UpdateWalletRequest{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletRequest) ProtoMessage() {}

func (x *UpdateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletRequest.ProtoReflect.Descriptor instead.
func (*UpdateWalletRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateWalletRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateWalletRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateWalletRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// Admin Messages
type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Users         []*Profile             `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserListResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UserListResponse) GetUsers() []*Profile {
	if x != nil {
		return x.Users
	}
	return nil
}

// Existing Messages (Updated)
type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{17}
}

func (x *ID) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDs) Reset() {
	*x = IDs{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDs) ProtoMessage() {}

func (x *IDs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDs.ProtoReflect.Descriptor instead.
func (*IDs) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{18}
}

func (x *IDs) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IDs) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	AadharNo      string                 `protobuf:"bytes,4,opt,name=aadhar_no,json=aadharNo,proto3" json:"aadhar_no,omitempty"`
	PancardNo     string                 `protobuf:"bytes,5,opt,name=pancard_no,json=pancardNo,proto3" json:"pancard_no,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Wallet        float32                `protobuf:"fixed32,8,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Licence       string                 `protobuf:"bytes,9,opt,name=licence,proto3" json:"licence,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,10,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{19}
}

func (x *Profile) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Profile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Profile) GetAadharNo() string {
	if x != nil {
		return x.AadharNo
	}
	return ""
}

func (x *Profile) GetPancardNo() string {
	if x != nil {
		return x.PancardNo
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Profile) GetWallet() float32 {
	if x != nil {
		return x.Wallet
	}
	return 0
}

func (x *Profile) GetLicence() string {
	if x != nil {
		return x.Licence
	}
	return ""
}

func (x *Profile) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *Profile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Profile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	House         string                 `protobuf:"bytes,3,opt,name=house,proto3" json:"house,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Zip           uint32                 `protobuf:"varint,6,opt,name=zip,proto3" json:"zip,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{20}
}

func (x *Address) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Address) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetZip() uint32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Address) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddressList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressList) Reset() {
	*x = AddressList{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressList) ProtoMessage() {}

func (x *AddressList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressList.ProtoReflect.Descriptor instead.
func (*AddressList) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{21}
}

func (x *AddressList) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Password struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword     string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,4,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Password) Reset() {
	*x = Password{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{22}
}

func (x *Password) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Password) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *Password) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *Password) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

// Vehicle details message (kept for reference, may be moved to fleet service)
type Vehicle struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	VehicleId           uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	VehicleType         string                 `protobuf:"bytes,2,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehicleTransmission string                 `protobuf:"bytes,3,opt,name=vehicle_transmission,json=vehicleTransmission,proto3" json:"vehicle_transmission,omitempty"`
	VehicleFuelType     string                 `protobuf:"bytes,4,opt,name=vehicle_fuel_type,json=vehicleFuelType,proto3" json:"vehicle_fuel_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ulimateuser_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_internal_pb_ulimateuser_user_proto_rawDescGZIP(), []int{23}
}

func (x *Vehicle) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Vehicle) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *Vehicle) GetVehicleTransmission() string {
	if x != nil {
		return x.VehicleTransmission
	}
	return ""
}

func (x *Vehicle) GetVehicleFuelType() string {
	if x != nil {
		return x.VehicleFuelType
	}
	return ""
}

var File_internal_pb_ulimateuser_user_proto protoreflect.FileDescriptor

const file_internal_pb_ulimateuser_user_proto_rawDesc = "" +
	"\n" +
	"\"internal/pb/ulimateuser/user.proto\x12\vulimateuser\"\t\n" +
	"\aNoParam\"\xb0\x01\n" +
	"\bResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.ulimateuser.Response.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x12\x14\n" +
	"\x04data\x18\x04 \x01(\tH\x00R\x04data\"\x1b\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01B\t\n" +
	"\apayload\"\x93\x01\n" +
	"\rSignupRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\\\n" +
	"\x0eSignupResponse\x121\n" +
	"\bresponse\x18\x01 \x01(\v2\x15.ulimateuser.ResponseR\bresponse\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"4\n" +
	"\n" +
	"OtpRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"q\n" +
	"\rLoginResponse\x121\n" +
	"\bresponse\x18\x01 \x01(\v2\x15.ulimateuser.ResponseR\bresponse\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"t\n" +
	"\x0fProfileResponse\x121\n" +
	"\bresponse\x18\x01 \x01(\v2\x15.ulimateuser.ResponseR\bresponse\x12.\n" +
	"\aprofile\x18\x02 \x01(\v2\x14.ulimateuser.ProfileR\aprofile\"\xd7\x01\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1b\n" +
	"\taadhar_no\x18\x05 \x01(\tR\baadharNo\x12\x1d\n" +
	"\n" +
	"pancard_no\x18\x06 \x01(\tR\tpancardNo\x12\x18\n" +
	"\alicence\x18\a \x01(\tR\alicence\"\x96\x01\n" +
	"\x11AddAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05house\x18\x02 \x01(\tR\x05house\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x05 \x01(\rR\x03zip\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\"\xa9\x01\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x14\n" +
	"\x05house\x18\x03 \x01(\tR\x05house\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x06 \x01(\rR\x03zip\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\"|\n" +
	"\x13AddressListResponse\x121\n" +
	"\bresponse\x18\x01 \x01(\v2\x15.ulimateuser.ResponseR\bresponse\x122\n" +
	"\taddresses\x18\x02 \x03(\v2\x14.ulimateuser.AddressR\taddresses\"\xa1\x01\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x04 \x01(\tR\x0fconfirmPassword\"\x97\x01\n" +
	"\x15UploadDocumentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12#\n" +
	"\rdocument_type\x18\x02 \x01(\tR\fdocumentType\x12#\n" +
	"\rdocument_data\x18\x03 \x01(\fR\fdocumentData\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\"]\n" +
	"\x0eWalletResponse\x121\n" +
	"\bresponse\x18\x01 \x01(\v2\x15.ulimateuser.ResponseR\bresponse\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x02R\abalance\"d\n" +
	"\x13UpdateWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\"q\n" +
	"\x10UserListResponse\x121\n" +
	"\bresponse\x18\x01 \x01(\v2\x15.ulimateuser.ResponseR\bresponse\x12*\n" +
	"\x05users\x18\x02 \x03(\v2\x14.ulimateuser.ProfileR\x05users\"\x14\n" +
	"\x02ID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\".\n" +
	"\x03IDs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\xd5\x02\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1b\n" +
	"\taadhar_no\x18\x04 \x01(\tR\baadharNo\x12\x1d\n" +
	"\n" +
	"pancard_no\x18\x05 \x01(\tR\tpancardNo\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x16\n" +
	"\x06wallet\x18\b \x01(\x02R\x06wallet\x12\x18\n" +
	"\alicence\x18\t \x01(\tR\alicence\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\n" +
	" \x01(\bR\tisBlocked\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xda\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x14\n" +
	"\x05house\x18\x03 \x01(\tR\x05house\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x06 \x01(\rR\x03zip\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"A\n" +
	"\vAddressList\x122\n" +
	"\taddresses\x18\x01 \x03(\v2\x14.ulimateuser.AddressR\taddresses\"\x94\x01\n" +
	"\bPassword\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x04 \x01(\tR\x0fconfirmPassword\"\xaa\x01\n" +
	"\aVehicle\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12!\n" +
	"\fvehicle_type\x18\x02 \x01(\tR\vvehicleType\x121\n" +
	"\x14vehicle_transmission\x18\x03 \x01(\tR\x13vehicleTransmission\x12*\n" +
	"\x11vehicle_fuel_type\x18\x04 \x01(\tR\x0fvehicleFuelType2\xae\t\n" +
	"\vUserService\x12A\n" +
	"\x06Signup\x12\x1a.ulimateuser.SignupRequest\x1a\x1b.ulimateuser.SignupResponse\x12;\n" +
	"\tVerifyOtp\x12\x17.ulimateuser.OtpRequest\x1a\x15.ulimateuser.Response\x12>\n" +
	"\x05Login\x12\x19.ulimateuser.LoginRequest\x1a\x1a.ulimateuser.LoginResponse\x12;\n" +
	"\n" +
	"GetProfile\x12\x0f.ulimateuser.ID\x1a\x1c.ulimateuser.ProfileResponse\x12I\n" +
	"\rUpdateProfile\x12!.ulimateuser.UpdateProfileRequest\x1a\x15.ulimateuser.Response\x12C\n" +
	"\n" +
	"AddAddress\x12\x1e.ulimateuser.AddAddressRequest\x1a\x15.ulimateuser.Response\x12I\n" +
	"\rUpdateAddress\x12!.ulimateuser.UpdateAddressRequest\x1a\x15.ulimateuser.Response\x127\n" +
	"\rDeleteAddress\x12\x0f.ulimateuser.ID\x1a\x15.ulimateuser.Response\x12A\n" +
	"\fGetAddresses\x12\x0f.ulimateuser.ID\x1a .ulimateuser.AddressListResponse\x12K\n" +
	"\x0eChangePassword\x12\".ulimateuser.ChangePasswordRequest\x1a\x15.ulimateuser.Response\x12K\n" +
	"\x0eUploadDocument\x12\".ulimateuser.UploadDocumentRequest\x1a\x15.ulimateuser.Response\x125\n" +
	"\vGetDocument\x12\x0f.ulimateuser.ID\x1a\x15.ulimateuser.Response\x128\n" +
	"\x0eDeleteDocument\x12\x0f.ulimateuser.ID\x1a\x15.ulimateuser.Response\x12@\n" +
	"\x10GetWalletBalance\x12\x0f.ulimateuser.ID\x1a\x1b.ulimateuser.WalletResponse\x12N\n" +
	"\x13UpdateWalletBalance\x12 .ulimateuser.UpdateWalletRequest\x1a\x15.ulimateuser.Response\x123\n" +
	"\tBlockUser\x12\x0f.ulimateuser.ID\x1a\x15.ulimateuser.Response\x125\n" +
	"\vUnblockUser\x12\x0f.ulimateuser.ID\x1a\x15.ulimateuser.Response\x12B\n" +
	"\vGetAllUsers\x12\x14.ulimateuser.NoParam\x1a\x1d.ulimateuser.UserListResponseBYZWgithub.com/yourorg/ultimate-rent-car/ultimate-rent-user-service/internal/pb/ulimateuserb\x06proto3"

var (
	file_internal_pb_ulimateuser_user_proto_rawDescOnce sync.Once
	file_internal_pb_ulimateuser_user_proto_rawDescData []byte
)

func file_internal_pb_ulimateuser_user_proto_rawDescGZIP() []byte {
	file_internal_pb_ulimateuser_user_proto_rawDescOnce.Do(func() {
		file_internal_pb_ulimateuser_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_ulimateuser_user_proto_rawDesc), len(file_internal_pb_ulimateuser_user_proto_rawDesc)))
	})
	return file_internal_pb_ulimateuser_user_proto_rawDescData
}

var file_internal_pb_ulimateuser_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_ulimateuser_user_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_internal_pb_ulimateuser_user_proto_goTypes = []any{
	(Response_Status)(0),          // 0: ulimateuser.Response.Status
	(*NoParam)(nil),               // 1: ulimateuser.NoParam
	(*Response)(nil),              // 2: ulimateuser.Response
	(*SignupRequest)(nil),         // 3: ulimateuser.SignupRequest
	(*SignupResponse)(nil),        // 4: ulimateuser.SignupResponse
	(*OtpRequest)(nil),            // 5: ulimateuser.OtpRequest
	(*LoginRequest)(nil),          // 6: ulimateuser.LoginRequest
	(*LoginResponse)(nil),         // 7: ulimateuser.LoginResponse
	(*ProfileResponse)(nil),       // 8: ulimateuser.ProfileResponse
	(*UpdateProfileRequest)(nil),  // 9: ulimateuser.UpdateProfileRequest
	(*AddAddressRequest)(nil),     // 10: ulimateuser.AddAddressRequest
	(*UpdateAddressRequest)(nil),  // 11: ulimateuser.UpdateAddressRequest
	(*AddressListResponse)(nil),   // 12: ulimateuser.AddressListResponse
	(*ChangePasswordRequest)(nil), // 13: ulimateuser.ChangePasswordRequest
	(*UploadDocumentRequest)(nil), // 14: ulimateuser.UploadDocumentRequest
	(*WalletResponse)(nil),        // 15: ulimateuser.WalletResponse
	(*UpdateWalletRequest)(nil),   // 16: ulimateuser.UpdateWalletRequest
	(*UserListResponse)(nil),      // 17: ulimateuser.UserListResponse
	(*ID)(nil),                    // 18: ulimateuser.ID
	(*IDs)(nil),                   // 19: ulimateuser.IDs
	(*Profile)(nil),               // 20: ulimateuser.Profile
	(*Address)(nil),               // 21: ulimateuser.Address
	(*AddressList)(nil),           // 22: ulimateuser.AddressList
	(*Password)(nil),              // 23: ulimateuser.Password
	(*Vehicle)(nil),               // 24: ulimateuser.Vehicle
}
var file_internal_pb_ulimateuser_user_proto_depIdxs = []int32{
	0,  // 0: ulimateuser.Response.status:type_name -> ulimateuser.Response.Status
	2,  // 1: ulimateuser.SignupResponse.response:type_name -> ulimateuser.Response
	2,  // 2: ulimateuser.LoginResponse.response:type_name -> ulimateuser.Response
	2,  // 3: ulimateuser.ProfileResponse.response:type_name -> ulimateuser.Response
	20, // 4: ulimateuser.ProfileResponse.profile:type_name -> ulimateuser.Profile
	2,  // 5: ulimateuser.AddressListResponse.response:type_name -> ulimateuser.Response
	21, // 6: ulimateuser.AddressListResponse.addresses:type_name -> ulimateuser.Address
	2,  // 7: ulimateuser.WalletResponse.response:type_name -> ulimateuser.Response
	2,  // 8: ulimateuser.UserListResponse.response:type_name -> ulimateuser.Response
	20, // 9: ulimateuser.UserListResponse.users:type_name -> ulimateuser.Profile
	21, // 10: ulimateuser.AddressList.addresses:type_name -> ulimateuser.Address
	3,  // 11: ulimateuser.UserService.Signup:input_type -> ulimateuser.SignupRequest
	5,  // 12: ulimateuser.UserService.VerifyOtp:input_type -> ulimateuser.OtpRequest
	6,  // 13: ulimateuser.UserService.Login:input_type -> ulimateuser.LoginRequest
	18, // 14: ulimateuser.UserService.GetProfile:input_type -> ulimateuser.ID
	9,  // 15: ulimateuser.UserService.UpdateProfile:input_type -> ulimateuser.UpdateProfileRequest
	10, // 16: ulimateuser.UserService.AddAddress:input_type -> ulimateuser.AddAddressRequest
	11, // 17: ulimateuser.UserService.UpdateAddress:input_type -> ulimateuser.UpdateAddressRequest
	18, // 18: ulimateuser.UserService.DeleteAddress:input_type -> ulimateuser.ID
	18, // 19: ulimateuser.UserService.GetAddresses:input_type -> ulimateuser.ID
	13, // 20: ulimateuser.UserService.ChangePassword:input_type -> ulimateuser.ChangePasswordRequest
	14, // 21: ulimateuser.UserService.UploadDocument:input_type -> ulimateuser.UploadDocumentRequest
	18, // 22: ulimateuser.UserService.GetDocument:input_type -> ulimateuser.ID
	18, // 23: ulimateuser.UserService.DeleteDocument:input_type -> ulimateuser.ID
	18, // 24: ulimateuser.UserService.GetWalletBalance:input_type -> ulimateuser.ID
	16, // 25: ulimateuser.UserService.UpdateWalletBalance:input_type -> ulimateuser.UpdateWalletRequest
	18, // 26: ulimateuser.UserService.BlockUser:input_type -> ulimateuser.ID
	18, // 27: ulimateuser.UserService.UnblockUser:input_type -> ulimateuser.ID
	1,  // 28: ulimateuser.UserService.GetAllUsers:input_type -> ulimateuser.NoParam
	4,  // 29: ulimateuser.UserService.Signup:output_type -> ulimateuser.SignupResponse
	2,  // 30: ulimateuser.UserService.VerifyOtp:output_type -> ulimateuser.Response
	7,  // 31: ulimateuser.UserService.Login:output_type -> ulimateuser.LoginResponse
	8,  // 32: ulimateuser.UserService.GetProfile:output_type -> ulimateuser.ProfileResponse
	2,  // 33: ulimateuser.UserService.UpdateProfile:output_type -> ulimateuser.Response
	2,  // 34: ulimateuser.UserService.AddAddress:output_type -> ulimateuser.Response
	2,  // 35: ulimateuser.UserService.UpdateAddress:output_type -> ulimateuser.Response
	2,  // 36: ulimateuser.UserService.DeleteAddress:output_type -> ulimateuser.Response
	12, // 37: ulimateuser.UserService.GetAddresses:output_type -> ulimateuser.AddressListResponse
	2,  // 38: ulimateuser.UserService.ChangePassword:output_type -> ulimateuser.Response
	2,  // 39: ulimateuser.UserService.UploadDocument:output_type -> ulimateuser.Response
	2,  // 40: ulimateuser.UserService.GetDocument:output_type -> ulimateuser.Response
	2,  // 41: ulimateuser.UserService.DeleteDocument:output_type -> ulimateuser.Response
	15, // 42: ulimateuser.UserService.GetWalletBalance:output_type -> ulimateuser.WalletResponse
	2,  // 43: ulimateuser.UserService.UpdateWalletBalance:output_type -> ulimateuser.Response
	2,  // 44: ulimateuser.UserService.BlockUser:output_type -> ulimateuser.Response
	2,  // 45: ulimateuser.UserService.UnblockUser:output_type -> ulimateuser.Response
	17, // 46: ulimateuser.UserService.GetAllUsers:output_type -> ulimateuser.UserListResponse
	29, // [29:47] is the sub-list for method output_type
	11, // [11:29] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_pb_ulimateuser_user_proto_init() }
func file_internal_pb_ulimateuser_user_proto_init() {
	if File_internal_pb_ulimateuser_user_proto != nil {
		return
	}
	file_internal_pb_ulimateuser_user_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Error)(nil),
		(*Response_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_ulimateuser_user_proto_rawDesc), len(file_internal_pb_ulimateuser_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_ulimateuser_user_proto_goTypes,
		DependencyIndexes: file_internal_pb_ulimateuser_user_proto_depIdxs,
		EnumInfos:         file_internal_pb_ulimateuser_user_proto_enumTypes,
		MessageInfos:      file_internal_pb_ulimateuser_user_proto_msgTypes,
	}.Build()
	File_internal_pb_ulimateuser_user_proto = out.File
	file_internal_pb_ulimateuser_user_proto_goTypes = nil
	file_internal_pb_ulimateuser_user_proto_depIdxs = nil
}
